### ISSUE TITLE
DicomInputStream fails to parse part10 files from InputStream which skips less than 132 bytes by invoking skip(132)

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#1040]
`DicomInputStream` fails to parse part10 files from `InputStream` which skips less than 132 bytes by invoking `skip(132)`.
E.g.:
```
    public void testPart10SkipNotAllAtOnce() throws Exception {
        Attributes result;
        try (DicomInputStream in = new DicomInputStream(
                new BufferedInputStream(new FileInputStream("target/test-data/DICOMDIR")){
            @Override
            public synchronized long skip(long n) throws IOException {
                return super.skip(Math.min(n, 128L));
            }
        })) {
            in.setIncludeBulkData(IncludeBulkData.YES);
            result = in.readDataset();
        }
        Attributes attrs = result;
        Sequence seq = attrs.getSequence(null, Tag.DirectoryRecordSequence);
        assertEquals(44, seq.size());
   }
```
results in
```
org.dcm4che3.io.DicomStreamException: Not a DICOM Stream

	at org.dcm4che3.io.DicomInputStream.guessTransferSyntax(DicomInputStream.java:934)
	at org.dcm4che3.io.DicomInputStream.<init>(DicomInputStream.java:138)
	at org.dcm4che3.io.DicomInputStream.<init>(DicomInputStream.java:133)
	at org.dcm4che3.io.DicomInputStreamTest.testPart10SkipNotAllAtOnce(DicomInputStreamTest.java:27)
```

**Comment by gunterze** [comment]
Fixed by
- https://github.com/dcm4che/dcm4che/commit/86518c77871207b7572fbb6d15bd83256ce15985
- https://github.com/dcm4che/dcm4che/commit/537cde521fdf6927414b8e95d655e3a8b0ac1a7b
