### ISSUE TITLE
Include OpenCV native library for linux-armv7a in binary distribution package and dcm4che-jboss-modules.(zip|tar.gz)

### ISSUE THREAD

**Issue by antoniotorres** [dcm4che/dcm4che#1069]
**Describe the bug**
DCM4CHEE would not start because of missing opencv library on armv7a (Raspberry Pi 4). The following error presented when using [dcm4chee-arc-psql](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql) Docker image.

**To Reproduce**
1. On the Raspberry Pi download [dcm4chee-arc-psql](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql)
2. Build the docker image and other images needed to run project
3. Start the containers needed to run project
4. Print the logs `docker-compose exec -u 0 dcm4chee tail -f /opt/wildfly/standalone/log/server.log`

**Expected behavior**
DCM4CHEE should start without any error

**Screenshots**
Downloading the file manually and taking a look you can see the following structure where no .so is available for this arch:
```bash
curl -f http://maven.dcm4che.org/org/dcm4che/jai_imageio-jboss-modules/1.2-pre-dr-b04/jai_imageio-jboss-modules-1.2-pre-dr-b04.tar.gz | tar xz
```
![image](https://user-images.githubusercontent.com/4925102/144327758-f1cbf19c-827f-4590-a023-2880e8ca99e3.png)

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)

**Additional context**
`/opt/wildfly/standalone/log/server.log`
```bash
...
2021-12-01 15:34:01,901 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 106) WFLYUT0021: Registered web context: '/dcm4chee-arc' for server 'default-server'
2021-12-01 15:34:03,947 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 84) MSC000001: Failed to start service jboss.deployment.subunit."dcm4chee-arc-ear-5.24.2-psql.ear"."dcm4chee-arc-service-5.24.2.jar".component.ArchiveServiceImpl.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."dcm4chee-arc-ear-5.24.2-psql.ear"."dcm4chee-arc-service-5.24.2.jar".component.ArchiveServiceImpl.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:170)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:141)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:127)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:141)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
        ... 8 more
Caused by: javax.ejb.EJBException: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:268)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:416)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:68)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.component.singleton.StartupCountDownInterceptor.processInvocation(StartupCountDownInterceptor.java:25)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:168)
        ... 13 more
Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:85)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:174)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.AbstractMemberProducer.getReceiver(AbstractMemberProducer.java:123)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:158)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:180)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:794)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.util.Beans.injectBoundFields(Beans.java:345)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:356)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultInjector$1.proceed(DefaultInjector.java:71)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultInjector.inject(DefaultInjector.java:73)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.module.ejb.DynamicInjectionPointInjector.inject(DynamicInjectionPointInjector.java:61)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.module.ejb.SessionBeanInjectionTarget.inject(SessionBeanInjectionTarget.java:138)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionContext.inject(WeldInjectionContext.java:39)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:51)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionContext.inject(WeldInjectionContext.java:39)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:51)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ManagedReferenceFieldInjectionInterceptorFactory$ManagedReferenceFieldInjectionInterceptor.processInvocation(ManagedReferenceFieldInjectionInterceptorFactory.java:112)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.ManagedReferenceFieldInjectionInterceptorFactory$ManagedReferenceFieldInjectionInterceptor.processInvocation(ManagedReferenceFieldInjectionInterceptorFactory.java:112)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.weld@24.0.1.Final//org.jboss.as.weld.interceptors.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:111)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@24.0.1.Final//org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
        at org.jboss.invocation@1.6.0.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@24.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:254)
        ... 28 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.core@3.1.7.SP1//org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83)
        ... 68 more
Caused by: java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.dcm4che.imageio@5.24.2//org.opencv.osgi.OpenCVNativeLoader.init(OpenCVNativeLoader.java:17)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.opencv.NativeJLSImageWriter.<clinit>(NativeJLSImageWriter.java:79)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.opencv.NativeJLSImageWriterSpi.createWriterInstance(NativeJLSImageWriterSpi.java:81)
        at java.desktop/javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
        at java.desktop/javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:849)
        at java.desktop/javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:833)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.imageio.codec.ImageWriterFactory.getImageWriterFromImageIOServiceRegistry(ImageWriterFactory.java:245)
        at org.dcm4che.imageio@5.24.2//org.dcm4che3.imageio.codec.ImageWriterFactory.getImageWriter(ImageWriterFactory.java:237)
        at deployment.dcm4chee-arc-ear-5.24.2-psql.ear.dcm4chee-arc-service-5.24.2.jar//org.dcm4chee.arc.impl.ArchiveDeviceProducer.initImageWriterFactory(ArchiveDeviceProducer.java:192)
        at deployment.dcm4chee-arc-ear-5.24.2-psql.ear.dcm4chee-arc-service-5.24.2.jar//org.dcm4chee.arc.impl.ArchiveDeviceProducer.init(ArchiveDeviceProducer.java:111)
        ... 73 more

2021-12-01 15:34:04,183 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dcm4chee-arc-ear-5.24.2-psql.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"dcm4chee-arc-ear-5.24.2-psql.ear\".\"dcm4chee-arc-service-5.24.2.jar\".component.ArchiveServiceImpl.START" => "java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.ejb.EJBException: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
    Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke private void org.dcm4chee.arc.impl.ArchiveDeviceProducer.init() on org.dcm4chee.arc.impl.ArchiveDeviceProducer@ea3b80
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]"}}
2021-12-01 15:34:04,216 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0010: Deployed "dcm4chee-arc-ui2-5.24.2.war" (runtime-name : "dcm4chee-arc-ui2-5.24.2.war")
2021-12-01 15:34:04,217 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0010: Deployed "dcm4chee-arc-ear-5.24.2-psql.ear" (runtime-name : "dcm4chee-arc-ear-5.24.2-psql.ear")
2021-12-01 15:34:04,221 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.subunit."dcm4chee-arc-ear-5.24.2-psql.ear"."dcm4chee-arc-service-5.24.2.jar".component.ArchiveServiceImpl.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
WFLYCTL0448: 2 additional services are down due to their dependencies being missing or failed
2021-12-01 15:34:04,563 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
2021-12-01 15:34:04,583 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 24.0.1.Final (WildFly Core 16.0.1.Final) started (with errors) in 75396ms - Started 2901 of 3121 services (7 services failed or missing dependencies, 455 services are lazy, passive or on-demand)
2021-12-01 15:34:04,590 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0062: Http management interface listening on http://0.0.0.0:9990/management and https://0.0.0.0:9993/management
2021-12-01 15:34:04,591 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0053: Admin console listening on http://0.0.0.0:9990 and https://0.0.0.0:9993
```

**Comment by antoniotorres** [comment]
Not sure where is the best place to write the issue, also wrote it on: https://github.com/dcm4che/jai-imageio-jboss-modules/issues/1

**Comment by hczedik** [comment]
FYI @nroduit.

**Comment by nroduit** [comment]
1) Concerning the [dcm4che](https://sourceforge.net/projects/dcm4che/files/dcm4che3/5.24.2/) toolkit, it should work. The native library is used with the commands (dcm2dcm, dcm2jpg, storescu).
At the first launch of one of these commands, [the library is downloaded ](https://github.com/nroduit/mvn-repo/tree/master/org/weasis/thirdparty/org/opencv/libopencv_java)because not distributed in dcm4che-5.24.2-bin.zip.

2) For dcm4chee (PACS), I think that the library is not downloaded automatically. The easiest way would be to add it manually.

I think the best would be to make docker images directly in multi-architecture mode (linux/amd64, linux/arm64, linux/arm/v7) by including the native library and the openjdk adapted to the system. Especially since there is a growing interest in ARM to have less energy-consuming infrastructures.

**Comment by gunterze** [comment]
Including `modules/org/dcm4che/imageio/main/lib/linux-armv7a/libopencv_java.so` into `dcm4che-jboss-modules.(zip|tar.gz)` is **not** sufficient to run provided docker image `dcm4che/dcm4chee-arc-psql:5.25.0[:secure[-ui]]` on processors with armv7a architecture! You will probably also need to use a different base image than `adoptopenjdk:11.0.11_9-jdk-hotspot-focal` of `dcm4che/wildfly:ffmpeg-24.0.1-15.0.2` (https://github.com/dcm4che-dockerfiles/wildfly ). Anyone is welcome providing an alternative Dockerfile-armv7a and testing on armv7a processors.

**Comment by nroduit** [comment]
This idea is to inherit a multi-architecture image => `FROM --platform=$BUILDPLATFORM adoptopenjdk:11-hotspot-focal` and then build it:
`docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t dcm4che/dcm4chee-arc-psql:latest .`

I guess there might be some adaptation to work properly on all systems like adapting the native library download. It would also be nice to make it directly a GitHub action that publishes automatically on docker hub.  I can propose a first version.

**Comment by antoniotorres** [comment]
@nroduit I created a PR for the wildfly docker image that does the building and pushing with github actions. The process starts when someone publishes a release on Github. I think is the best way to do it, but I can help to adapted to another other ways.

The issue with `adoptopenjdk:11-hotspot-focal` is that is only built for amd64 and it also appears to be deprecated. On this PR I propose it is changed to [eclipse-temurin:11.0.13_8-jdk-focal](https://hub.docker.com/_/eclipse-temurin?tab=tags&page=1&name=11.0.13_8-jdk-focal)

https://github.com/dcm4che-dockerfiles/wildfly/pull/2

**Comment by gunterze** [comment]
http://maven.dcm4che.org/org/dcm4che/dcm4che-jboss-modules/5.25.0/dcm4che-jboss-modules-5.25.0.tar.gz, included by https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/blob/master/Dockerfile#L11 :
```
    && curl -f http://maven.dcm4che.org/org/dcm4che/dcm4che-jboss-modules/$DCM4CHE_VERSION/dcm4che-jboss-modules-${DCM4CHE_VERSION}.tar.gz | tar xz \
```
into the archive docker image contains native libraries for all supported platforms - we may optimize it later to just extract the version for the specified platform of the build.

There is already a Pull Request ( https://github.com/dcm4che-dockerfiles/wildfly/pull/2 ) which I did not yet found time to review (oops @antoniotorres was faster :))

**Comment by nroduit** [comment]
@antoniotorres You were really too quick!
I would replace 11.0.13_8-jdk-focal by 11-jdk-focal to have the latest release of jdk 11 when building.

**Comment by gunterze** [comment]
Have also not yet found time to test and make necessary adjustments to get the archive running on java 17 - just to let you know, I am aware we should move to the latest LTS version of the JVM.

**Comment by nroduit** [comment]
JDK 17 does not allow reflective access of private fields anymore, so you have to be careful with [this](https://blogs.oracle.com/javamagazine/java-runtime-encapsulation-internals).

@antoniotorres To ensure crosscompilation, I think it is necessary to add `FROM --platform=$BUILDPLATFORM 11-jdk-focal`, see https://docs.docker.com/buildx/working-with-buildx/
