### ISSUE TITLE
dcmqrscp failure

### ISSUE THREAD

**Issue by amaljesudas** [dcm4che/dcm4che#1177]
I run dcmqrscp with the following command:
dcmqrscp -b DCMQRSCP:11112 --dicomdir C:\Data --all-storage

When I perform query, it fails and the below error stack is obtained showing a DicomServiceException:

20:25:07.424 INFO  - Start TCP Listener on 0.0.0.0/0.0.0.0:11112
20:25:11.158 INFO  - Accept connection Socket[addr=/10.77.65.65,port=51048,localport=11112]
20:25:11.166 DEBUG - /10.77.65.65:11112<-/10.77.65.65:51048(1): enter state: Sta2 - Transport connection open
20:25:11.169 INFO  - DCMQRSCP<-SCU(1) >> A-ASSOCIATE-RQ
20:25:11.170 DEBUG - A-ASSOCIATE-RQ[
  calledAET: DCMQRSCP
  callingAET: SCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 2.16.840.1
  implVersionName: MergeCOM3_5_1_0
  maxPDULength: 64234
  maxOpsInvoked/maxOpsPerformed: 1/1
  PresentationContext[id: 1
    as: 1.2.840.10008.5.1.4.31 - Modality Worklist Information Model - FIND
    ts: 1.2.840.10008.1.2.1 - Explicit VR Little Endian
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
    ts: 1.2.840.10008.1.2.2 - Explicit VR Big Endian (Retired)
  ]
]
20:25:11.177 DEBUG - DCMQRSCP<-SCU(1): enter state: Sta3 - Awaiting local A-ASSOCIATE response primitive
20:25:11.177 INFO  - DCMQRSCP<-SCU(1) << A-ASSOCIATE-AC
20:25:11.177 DEBUG - A-ASSOCIATE-AC[
  calledAET: DCMQRSCP
  callingAET: SCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 1.2.40.0.13.1.3
  implVersionName: dcm4che-5.25.1
  maxPDULength: 16378
  maxOpsInvoked/maxOpsPerformed: 1/1
  PresentationContext[id: 1
    result: 0 - acceptance
    ts: 1.2.840.10008.1.2.1 - Explicit VR Little Endian
  ]
]
20:25:11.177 DEBUG - DCMQRSCP<-SCU(1): enter state: Sta6 - Association established and ready for data transfer
20:25:11.180 INFO  - DCMQRSCP<-SCU(1) >> 2:C-FIND-RQ[pcid=1, prior=0
  cuid=1.2.840.10008.5.1.4.31 - Modality Worklist Information Model - FIND
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian]
20:25:11.180 DEBUG - DCMQRSCP<-SCU(1) >> 2:C-FIND-RQ Command:
(0000,0002) UI [1.2.840.10008.5.1.4.31] AffectedSOPClassUID
(0000,0100) US [32] CommandField
(0000,0110) US [2] MessageID
(0000,0700) US [0] Priority
(0000,0800) US [0] CommandDataSetType

20:25:11.188 DEBUG - DCMQRSCP<-SCU(1) >> 2:C-FIND-RQ Dataset receiving...
20:25:11.188 INFO  - DCMQRSCP<-SCU(1): processing 2:C-FIND-RQ[pcid=1, prior=0
  cuid=1.2.840.10008.5.1.4.31 - Modality Worklist Information Model - FIND
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian] failed. Caused by:
**org.dcm4che3.net.service.DicomServiceException: null
        at org.dcm4che3.net.service.DicomServiceRegistry.lookupService(DicomServiceRegistry.java:126)
        at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
        at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:474)
        at org.dcm4che3.net.Association.onDimseRQ(Association.java:755)
        at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:466)
        at org.dcm4che3.net.Association.handlePDataTF(Association.java:738)
        at org.dcm4che3.net.State$4.onPDataTF(State.java:108)
        at org.dcm4che3.net.Association.onPDataTF(Association.java:734)
        at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
        at org.dcm4che3.net.Association$2.run(Association.java:571)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)**
20:25:11.188 INFO  - DCMQRSCP<-SCU(1) << 2:C-FIND-RSP[pcid=1, status=122H
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian]
20:25:11.188 DEBUG - DCMQRSCP<-SCU(1) << 2:C-FIND-RSP Command:
(0000,0100) US [32800] CommandField
(0000,0120) US [2] MessageIDBeingRespondedTo
(0000,0800) US [257] CommandDataSetType
(0000,0900) US [290] Status

20:25:11.188 DEBUG - DCMQRSCP<-SCU(1): Service User did not consume 288 bytes of DIMSE data.
20:25:11.188 INFO  - DCMQRSCP<-SCU(1) >> A-RELEASE-RQ
20:25:11.188 DEBUG - DCMQRSCP<-SCU(1): enter state: Sta8 - Awaiting local A-RELEASE response primitive
20:25:11.188 INFO  - DCMQRSCP<-SCU(1) << A-RELEASE-RP
20:25:11.188 DEBUG - DCMQRSCP<-SCU(1): enter state: Sta13 - Awaiting Transport Connection Close Indication
20:25:11.188 DEBUG - DCMQRSCP<-SCU(1): closing Socket[addr=/10.77.65.65,port=51048,localport=11112] in 50 ms
20:25:11.257 INFO  - DCMQRSCP<-SCU(1): close Socket[addr=/10.77.65.65,port=51048,localport=11112]
20:25:11.257 DEBUG - DCMQRSCP<-SCU(1): enter state: Sta1 - Idle

What could I be possibly doing wrong?

Thanks in advance.

**Comment by gunterze** [comment]
`--dicomdir C:\Data` does not looks like a path to the DICOMDIR **file**

Anyway I got different errors, by specifying an existing directory or a path to which the current user has no r/w permission on Ubuntu Linux

**Comment by amaljesudas** [comment]
@gunterze  - Are you speculating that the error could be due to missing DICOMDIR file or folder permissions?
Can you shed some light on what could possibly cause the below errors:
org.dcm4che3.net.service.DicomServiceException: null
at org.dcm4che3.net.service.DicomServiceRegistry.lookupService(DicomServiceRegistry.java:126)

I am a newbie to dcm4che and Java environment, so am trying to learn as well.
Thanks.
