### ISSUE TITLE
Specific Character Set Error when modifying data using storescu

### ISSUE THREAD

**Issue by jssuttles** [dcm4che/dcm4che#1180]
**Describe the bug**
When using the storescu utility on a DICOM that has the GB18030 character set and modifying data like the accession number, an error is produced.

**To Reproduce**
1. Use something like following command line: `storescu -s 00081010=SOMETHING --prior-high --max-pdulen-rcv 4096 -c ORTHANC@127.0.0.1:6003 -b SOMETHING path_to_folder_with_character_set` 
   * Attached example DICOM [IM-0001-0018.txt](https://github.com/dcm4che/dcm4che/files/8653743/IM-0001-0018.txt)
   * convert by changing the extension from .txt to .dcm
3. See error:
Error: org.dcm4che3.data.IncompatibleSpecificCharacterSetException: Specific Character Sets [GB18030] and [] not compatible
	at org.dcm4che3.data.Attributes.add(Attributes.java:2348)
	at org.dcm4che3.data.Attributes.update(Attributes.java:2541)
	at org.dcm4che3.tool.common.CLIUtils.updateAttributes(CLIUtils.java:822)
	at org.dcm4che3.tool.storescu.StoreSCU.send(StoreSCU.java:461)
	at org.dcm4che3.tool.storescu.StoreSCU.sendFiles(StoreSCU.java:370)
	at org.dcm4che3.tool.storescu.StoreSCU.main(StoreSCU.java:278)

**Expected behavior**
The data is added to the files and successfully transferred to the destination.

**Comment by jssuttles** [comment]
Fixed by adding `-s 00080005 GB18030`

**Comment by jssuttles** [comment]
Actually, this causes an issue. Storescu is able to handle most other character sets, but is unable to handle GB18030 and ISO 2022 IR 58.

**Comment by jssuttles** [comment]
I think the `containsNonASCIIStringValues` function is suspicious. It does not check that the string coming in has any actual non-ASCII characters. For example, `ACTUAL_HEALTH` does not contain non-ASCII characters.
