### ISSUE TITLE
dcm4che can't store a particular CT

### ISSUE THREAD

**Issue by umberto-cappellini** [dcm4che/dcm4che#123]
when trying to dump:

`IOException during read of (7FE0,0010) #524288 @ 1254
java.io.EOFException
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:63)
	at org.dcm4che3.io.DicomInputStream.readFully(DicomInputStream.java:384)
	at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:730)
	at org.dcm4che3.tool.dcmdump.DcmDump.readValue(DcmDump.java:122)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:516)
	at org.dcm4che3.io.DicomInputStream.readDataset(DicomInputStream.java:444)
	at org.dcm4che3.tool.dcmdump.DcmDump.parse(DcmDump.java:87)
	at org.dcm4che3.tool.dcmdump.DcmDump.main(DcmDump.java:245)
`

[00010ccd.dcm.zip](https://github.com/dcm4che/dcm4che/files/1109035/00010ccd.dcm.zip)

**Comment by umberto-cappellini** [comment]
closing because the attached dcm file is missing pixels and the library correctly rejects it.

**Comment by SpiritZhangYP** [comment]
I have the same problem

**Comment by jayzhk** [comment]
Can you share your log files ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ljuillerat** [comment]
I have the same issue. Can it be corrected or is it a problem from images generated by CT ?
