### ISSUE TITLE
jpg2dcm conversion of MPEG-ES

### ISSUE THREAD

**Issue by rlking** [dcm4che/dcm4che#1251]
Cannot convert MPEG-ES file to dicom.  I did not have problems with MPEG-PS. The failure is

`PS > jpg2dcm.bat .\centaur.mpg .\centaur.dcm
jpg2dcm: Invalid MPEG2 start code 10EEC1E0H on position 5126
org.dcm4che3.imageio.codec.XPEGParserException: Invalid MPEG2 start code 10EEC1E0H on position 5126
        at org.dcm4che3.imageio.codec.mpeg.MPEG2Parser.nextPacket(MPEG2Parser.java:221)
        at org.dcm4che3.imageio.codec.mpeg.MPEG2Parser.<init>(MPEG2Parser.java:97)
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm$ContentType$2.newParser(Jpg2Dcm.java:302)
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.convert(Jpg2Dcm.java:225)
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.convert(Jpg2Dcm.java:177)
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.main(Jpg2Dcm.java:118)`

Output of ffprobe is:

`Input #0, mpegvideo, from './centaur.mpg':
  Duration: 00:00:14.08, bitrate: 320 kb/s
    Stream #0:0: Video: mpeg1video, yuv420p(tv), 320x240 [SAR 1:1 DAR 4:3], 320 kb/s, 29.97 fps, 29.97 tbr, 1200k tbn, 29.97 tbc
[FORMAT]
filename=./centaur.mpg
nb_streams=1
nb_programs=0
format_name=mpegvideo
format_long_name=raw MPEG video
start_time=N/A
duration=14.075400
size=563016
bit_rate=320000
probe_score=51
[/FORMAT]`

[centaur.zip](https://github.com/dcm4che/dcm4che/files/9799024/centaur.zip)

**Comment by rlking** [comment]
Not sure if this is a bug or a feature, and would also like to verify if this is a valid format for dicom.
Reading [sect_8.2.5](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.5.html) it should be a valid container

**Comment by gunterze** [comment]
Extended MPEG2Parser  to accept MPEG-ES streams starting with plain MPEG Video_Sequence_Header with start code `0x000001B3`.
