### ISSUE TITLE
jpg2dcm OutOfMemory error

### ISSUE THREAD

**Issue by navrkalpavel** [dcm4che/dcm4che#1259]
**Describe the bug**
I have dicom PET image [test.zip](https://github.com/dcm4che/dcm4che/files/9927694/test.zip). Transcoding image to the jpeg by dcm2jpg hangs on OutOfMemory error:

```
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at org.dcm4che3.image.ByteLookupTable.<init>(ByteLookupTable.java:13)
        at org.dcm4che3.image.LookupTableFactory.combineModalityVOILUT(LookupTableFactory.java:278)
        at org.dcm4che3.image.LookupTableFactory.createLUT(LookupTableFactory.java:236)
        at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.applyLUTs(DicomImageReader.java:703)
        at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.applyGrayscaleTransformations(DicomImageReader.java:485)
        at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:468)
        at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.readImageFromDicomInputStream(Dcm2Jpg.java:438)
        at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg$$Lambda$49/0x000000080015ee78.apply(Unknown Source)
        at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.convert(Dcm2Jpg.java:425)
        at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.mconvert(Dcm2Jpg.java:412)
        at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.main(Dcm2Jpg.java:381)

```
Thera are no LUT data in the image. Why is dcm4che trying to create lookup table for this image?

**Desktop (please complete the following information):**
 - OS: Linux
 - Version dcm4che 5.25.2
 - OpenJDK 17

**Comment by nroduit** [comment]
The values of WindowWidth and WindowCenter are not consistent with the values of RescaleSlope.
```
(0028,1050)	DS	WindowCenter		1
(0028,1051)	DS	WindowWidth		1
(0028,1052)	DS	RescaleIntercept	0
(0028,1053)	DS	RescaleSlope		3.51677E-10
(0028,1054)	LO	RescaleType		BQML
```
The size of LUT divides the WindowCenter by RescaleSlope when WindowCenter is different of 0 (exist).

Unfortunately, it seems not possible to pass WindowCenter to 0 in the parameters of the command (always converted to 1).

So a fix could be to add a new condition, see https://github.com/dcm4che/dcm4che/blob/master/dcm4che-image/src/main/java/org/dcm4che3/image/LookupTableFactory.java#L269-L275
```java
            if (w != 0 && w/m < inBits.maxValue() * 2) {
                size = Math.max(2,Math.abs(Math.round(w/m)));
                offset = Math.round((c-b)/m) - size/2;
            } else {
                offset = inBits.minValue();
                size = inBits.maxValue() - inBits.minValue() + 1;
            }``
