### ISSUE TITLE
ByteBuffer error in binary version 5.29.1 on Windows Server 2019

### ISSUE THREAD

**Issue by Codevya** [dcm4che/dcm4che#1291]
**Describe the bug**
Although it works fine on Windows 10/11 and Linux, the latest version of the binary gives the following error:

Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.copy(Jpg2Dcm.java:287)
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.convert(Jpg2Dcm.java:272)
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.convert(Jpg2Dcm.java:203)
        at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.main(Jpg2Dcm.java:134)

**To Reproduce**
1. Use bare metal windows server 2019
2. launch jpg2dcm.bat from powershell
3. Get the error
4. dicom file is still created but unreadable

**Screenshots**
![image](https://user-images.githubusercontent.com/53542036/215499179-0cd9325d-4870-48b6-bca3-5077e1ee1052.png)

**Desktop (please complete the following information):**
 - OS: Windows server 2019 Standard Edition

**Additional context**
Using the version  5.29.0 works fine out of the box

**Comment by nroduit** [comment]
I guess it's related to t[his issue](https://github.com/dcm4che/dcm4che/pull/536) and that using Java 8 is the cause.

The solution is to either upgrade to Java 11 or 17 or propose a code fix using `StreamUtils.safeBufferType(bb)`.
