### ISSUE TITLE
Toolkit opencv bug

### ISSUE THREAD

**Issue by keas9** [dcm4che/dcm4che#1319]
When trying to convert study (dcm2jpg) and use opencv lib I got error:
`[ERROR:[0@0.023](mailto:0@0.023)] global /Users/test/Documents/opencv/modules/imgcodecs/src/grfmt_dcm_jpegls.cpp (97) readData Decode JPEG-LS data error: Invalid JPEG-LS stream: the leading start byte (0xFF) for a JPEG marker was not found
Failed to convert /Users/test/tmp/STORAGE/DICOM/dicom/MR1_JLSL.dcm: w and h must be > 0
java.lang.IllegalArgumentException: w and h must be > 0
    at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:214)
    at java.desktop/java.awt.image.ComponentColorModel.createCompatibleWritableRaster(ComponentColorModel.java:2827)
    at org.weasis.opencv.op.ImageConversion.toBufferedImage(ImageConversion.java:80)
    at org.weasis.opencv.op.ImageConversion.toBufferedImage(ImageConversion.java:118)
    at org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:252)
    at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:458)
    at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.readImageFromDicomInputStream(Dcm2Jpg.java:438)
    at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.convert(Dcm2Jpg.java:425)
    at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.mconvert(Dcm2Jpg.java:412)
    at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.main(Dcm2Jpg.java:381)`

This issue starts from 5.29.2 version
Added dcm to debug [MR1_JLSL.zip](https://github.com/dcm4che/dcm4che/files/11833879/MR1_JLSL.zip)

**Comment by nroduit** [comment]
The segment marking the end of the JPEG-LS stream is invalid. The following error is thrown from the CharLS library since version 2.3:
`[ERROR:33@12.992] global /work/modules/imgcodecs/src/grfmt_dcm_jpegls.cpp (97) readData Decode JPEG-LS data error: Invalid JPEG-LS stream: the leading start byte (0xFF) for a JPEG marker was not found`

The end segment with odd-length padding is  '00 FF D9'  when it should be 'FF FF D9'.
```
nicolas@nicolas-P920:~$ xxd /home/nicolas/Téléchargements/MR1_JLSL.dcm | tail -n 2
000388c0: 35a6 3f82 2c11 2b00 ffd9 feff dde0 0000  5.?.,.+.........
000388d0: 0000                                     ..
```

Another padding possibility is 'FF D9 00' compliant with JPEG-LS (but not compliant with the DICOM standard).

Although I'm going to modify the library in the next release to make this image readable, it's important to report the problem to the tool that generates this JPEG-LS compression.
