### ISSUE TITLE
Transcoder: java.lang.ClassCastException

### ISSUE THREAD

**Issue by adrianog3** [dcm4che/dcm4che#1323]
Affected Library: dcm4che-imageio

When trying to transcode a dicom file with transfer syntax 1.2.840.10008.1.2.4.70 (JPEGLosslessSV1) to 1.2.840.10008.1.2.4.80 (JPEGLSLossless) the operation is successful, but when trying to transcode the output file to the original transfer syntax the following error happens:

`java.lang.ClassCastException: java.awt.image.DataBufferByte cannot be cast to java.awt.image.DataBufferShort
	at org.dcm4che3.image.BufferedImageUtils.convertShortsToBytes(BufferedImageUtils.java:169) ~[dcm4che-image-5.24.0.jar:5.24.0]
	at org.dcm4che3.imageio.codec.Transcoder.compressPixelData(Transcoder.java:579) ~[dcm4che-imageio-5.24.0.jar:5.24.0]
	at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:507) ~[dcm4che-imageio-5.24.0.jar:5.24.0]
	at org.dcm4che3.imageio.codec.Transcoder.access$800(Transcoder.java:71) ~[dcm4che-imageio-5.24.0.jar:5.24.0]
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:464) ~[dcm4che-imageio-5.24.0.jar:5.24.0]
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:576) ~[dcm4che-core-5.24.0.jar:5.24.0]
	at org.dcm4che3.io.DicomInputStream.readAllAttributes(DicomInputStream.java:483) ~[dcm4che-core-5.24.0.jar:5.24.0]
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:438) ~[dcm4che-imageio-5.24.0.jar:5.24.0]
	at org.example.Application.transcode(Application.java:63) [classes/:?]
	at org.example.Application.main(Application.java:46) [classes/:?]`

In my tests, only a few files failed to revert the transfer syntax to the original value.

To reproduce the error i created a repository with instructions and a sample: https://github.com/adrianog3/dcm4che-transcode-issue

The error does not depend on the operating system.

**Comment by adrianog3** [comment]
Hi guys, i found the solution and open a PR for code review. 

This is the first time I open a PR for an open source code, so any suggestions, criticisms or changes are welcome.

https://github.com/dcm4che/dcm4che/pull/1324
