### ISSUE TITLE
readDataset() throw exception

### ISSUE THREAD

**Issue by hevenwus** [dcm4che/dcm4che#1356]
with version 5.30.0 read dicom file throw exception

The code is as follows.
```
File source = new File("D:\\test.dcm");
inputStream = new DicomInputStream(source);
Attributes dataset = inputStream.readDataset();
```
readDataset() throw exception:
WARN   --- [main]org.dcm4che3.io.DicomInputStream         : Unrecognized VR code: 0000H for (0000,0000) - treat as UL
WARN   --- [main]org.dcm4che3.io.DicomInputStream         : Unrecognized VR code: 0000H for (0000,0000) - treat as UL
java.io.EOFException
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:74)
	at org.dcm4che3.io.DicomInputStream.readFully(DicomInputStream.java:393)
	at org.dcm4che3.io.DicomInputStream.readHeader(DicomInputStream.java:426)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:557)
	at org.dcm4che3.io.DicomInputStream.readDataset(DicomInputStream.java:503)
	at org.dcm4che3.io.DicomInputStream.readDataset(DicomInputStream.java:487)

I found a lot of empty characters added to the end of the file。

**Comment by yanhaoxue** [comment]
I encountered the same problem, how to solve it?

**Comment by Orgins** [comment]
I encountered the same problem, how to solve it?
