### ISSUE TITLE
Cannot invoke "org.dcm4che3.opencv.StreamSegment.getImageDescriptor()" because "seg" is null

### ISSUE THREAD

**Issue by SaluRamos** [dcm4che/dcm4che#1403]
**Describe the bug**
```
03:36:01.918 [main] DEBUG org.dcm4che3.imageio.plugins.dcm.DicomImageReader -- Decompressor: org.dcm4che3.opencv.NativeImageReader
03:36:01.923 [main] DEBUG org.dcm4che3.imageio.plugins.dcm.DicomImageReader -- Start decompressing frame #1
03:36:01.952 [main] ERROR org.dcm4che3.opencv.StreamSegment -- Building FileStreamSegment from SegmentedInputImageStream
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.io.RandomAccessFile javax.imageio.stream.FileCacheImageInputStream.cache accessible: module java.desktop does not "opens javax.imageio.stream" to module dcm4che.imageio.opencv
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at dcm4che.imageio.opencv@5.31.2/org.dcm4che3.opencv.StreamSegment.getFileStreamSegment(StreamSegment.java:129)
	at dcm4che.imageio.opencv@5.31.2/org.dcm4che3.opencv.StreamSegment.getStreamSegment(StreamSegment.java:98)
	at dcm4che.imageio.opencv@5.31.2/org.dcm4che3.opencv.NativeImageReader.getNativeImage(NativeImageReader.java:260)
	at dcm4che.imageio.opencv@5.31.2/org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:251)
	at dcm4che.imageio@5.31.2/org.dcm4che3.imageio.plugins.dcm.DicomImageReader.readRaster(DicomImageReader.java:375)
	at com.webkriativa.noahviewer@0.4/com.webkriativa.noahviewer.graphics.FrameSetVolume.loadHounsfieldValue(FrameSetVolume.java:98)
	at com.webkriativa.noahviewer@0.4/com.webkriativa.noahviewer.graphics.FrameSetVolume.<init>(FrameSetVolume.java:35)
	at com.webkriativa.noahviewer@0.4/com.webkriativa.noahviewer.MRETest.loadImage(MRETest.java:68)
	at com.webkriativa.noahviewer@0.4/com.webkriativa.noahviewer.MRETest.main(MRETest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1085)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.2/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 2 executed, 3 up-to-date
fev. 24, 2024 3:36:01 AM org.opencv.osgi.OpenCVNativeLoader init
INFORMA��ES: Successfully loaded OpenCV native library.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1085)
Caused by: java.lang.NullPointerException: Cannot invoke "org.dcm4che3.opencv.StreamSegment.getImageDescriptor()" because "seg" is null
	at dcm4che.imageio.opencv@5.31.2/org.dcm4che3.opencv.NativeImageReader.getNativeImage(NativeImageReader.java:261)
	at dcm4che.imageio.opencv@5.31.2/org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:251)
	at dcm4che.imageio@5.31.2/org.dcm4che3.imageio.plugins.dcm.DicomImageReader.readRaster(DicomImageReader.java:375)

```

Java correto 17.0.9, with gradle and modules.

this is my build.gradle

```
plugins {
    id "java"
    id "application"
    id "org.javamodularity.moduleplugin" version "1.8.12"
}

group "com.myapp"
version "0.1"

var openCVNativesWindowsPath = "libs/dcm4che-5.31.2/lib/windows-x86-64"

repositories {
    mavenCentral()
}

sourceCompatibility = "17"
targetCompatibility = "17"

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

application {
    mainModule = "com.webkriativa.noahviewer"
    mainClass = "com.webkriativa.noahviewer.Main"
}

dependencies {
    implementation files("libs/dcm4che-5.31.2/lib/angus-activation-2.0.1.jar")
    implementation files("libs/dcm4che-5.31.2/lib/clibwrapper_jiio-1.2-pre-dr-b04.jar")
    implementation files("libs/dcm4che-5.31.2/lib/commons-cli-1.6.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-audit-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-conf-api-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-conf-api-hl7-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-conf-ldap-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-conf-ldap-audit-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-conf-ldap-hl7-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-conf-ldap-imageio-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-core-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-dcmr-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-deident-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-dict-priv-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-emf-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-hl7-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-image-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-imageio-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-imageio-opencv-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-imageio-rle-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-json-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-mime-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-net-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-net-audit-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-net-hl7-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-qstar-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-soundex-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-agfa2dcm-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-agfa2sr-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-common-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcm2dcm-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcm2jpg-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcm2json-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcm2pdf-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcm2str-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcm2xml-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcmassoc-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcmbenchmark-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcmdir-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcmdump-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcmldap-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcmqrscp-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-dcmvalidate-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-deidentify-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-emf2sf-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-findscu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-fixlo2un-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-getscu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-hl72xml-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-hl7pdq-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-hl7pix-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-hl7rcv-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-hl7snd-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-ianscp-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-ianscu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-ihe-modality-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-jpg2dcm-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-json2dcm-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-json2index-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-json2props-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-json2rst-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-maskpxdata-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-mkkos-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-movescu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-mppsscp-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-mppsscu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-pdf2dcm-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-planarconfig-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-qstar-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-stgcmtscu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-storescp-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-storescu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-stowrs-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-stowrsd-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-swappxdata-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-syslog-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-syslogd-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-tpl2xml-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-upsscu-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-wadors-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-wadows-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-xml2dcm-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-xml2hl7-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-tool-xroad-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-ws-rs-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-xdsi-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/dcm4che-xroad-5.31.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/gmbal-api-only-4.0.3.jar")
    implementation files("libs/dcm4che-5.31.2/lib/istack-commons-runtime-4.1.1.jar")
//    implementation files("libs/dcm4che-5.31.2/lib/jai_imageio-1.2-pre-dr-b04.jar")
    implementation files("libs/dcm4che-5.31.2/lib/jakarta.activation-api-2.1.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/jakarta.json-api-2.1.2.jar")
    implementation files("libs/dcm4che-5.31.2/lib/jakarta.xml.bind-api-4.0.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/jakarta.xml.soap-api-3.0.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/jakarta.xml.ws-api-4.0.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/jaxb-core-4.0.1.jar")
    implementation files("libs/dcm4che-5.31.2/lib/jaxb-runtime-4.0.1.jar")
    implementation files("libs/dcm4che-5.31.2/lib/logback-classic-1.4.14.jar")
    implementation files("libs/dcm4che-5.31.2/lib/logback-core-1.4.14.jar")
    implementation files("libs/dcm4che-5.31.2/lib/mimepull-1.10.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/parsson-1.1.3.jar")
    implementation files("libs/dcm4che-5.31.2/lib/policy-4.0.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/rt-4.0.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/saaj-impl-3.0.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/slf4j-api-2.0.9.jar")
    implementation files("libs/dcm4che-5.31.2/lib/stax-ex-2.1.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/streambuffer-2.1.0.jar")
    implementation files("libs/dcm4che-5.31.2/lib/weasis-core-img-4.8.1.jar")

    compileOnly("org.projectlombok:lombok:1.18.28")
    annotationProcessor("org.projectlombok:lombok:1.18.28")
    testCompileOnly("org.projectlombok:lombok:1.18.28")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.28")
}

run {
    jvmArgs = ['-Djava.library.path="' + lwjglNativesPath + ';' + openCVNativesWindowsPath + ';' + simpleitkLibPath + '"', '--add-opens', 'java.desktop/javax.imageio.stream=ALL-UNNAMED', '--add-opens', 'java.' +
            'base/java.io=ALL-UNNAMED']
}
```

**Comment by nroduit** [comment]
Integration with a Java module is different from that of the classpath. You need to specify accesses, see this [post](https://www.java4coding.com/contents/java/java9features/java-module-opens).

**Comment by SaluRamos** [comment]
> Integration with a Java module is different from that of the classpath. You need to specify accesses, see this [post](https://www.java4coding.com/contents/java/java9features/java-module-opens).

After studying more about modules I managed to understand my error and solved it as follows:

jvmArgs = ['-Djava.library.path="' + lwjglNativesPath + ';' + openCVNativesWindowsPath + ';' + simpleitkLibPath + '"', '--add-opens', 'java.desktop/javax.imageio.stream=dcm4che.imageio.opencv',
               '--add-opens', 'java.base/java.io=dcm4che.imageio.opencv']

**Comment by SaluRamos** [comment]
the jvmArgs solution worked only for run task, not for jlink task, when running the generated executable got:

```
java.lang.NullPointerException: Cannot invoke "org.dcm4che3.opencv.StreamSegment.getImageDescriptor()" because "seg" is null
        at com.webkriativa.noahviewer.merged.module@0.5/org.dcm4che3.opencv.NativeImageReader.getNativeImage(NativeImageReader.java:261)
        at com.webkriativa.noahviewer.merged.module@0.5/org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:251)
        at com.webkriativa.noahviewer.merged.module@0.5/org.dcm4che3.imageio.plugins.dcm.DicomImageReader.readRaster(DicomImageReader.java:375)
        at com.webkriativa.noahviewer@0.5/com.webkriativa.noahviewer.io.FrameSetLoader.loadCompressedSlice(FrameSetLoader.java:229)
```

hope you dont mind calling your help @nroduit

**Comment by smitalimaye** [comment]
I am getting exact same error when I run - 
java -classpath dicom/regression/target/dicom-regression-1.0.0.jar --add-opens java.desktop/javax.imageio.stream=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED com.susom.deid.regression.ScrubUtil
```
21:30:40.263 [main] DEBUG org.dcm4che3.imageio.plugins.dcm.DicomImageReader -- Decompressor: org.dcm4che3.opencv.NativeImageReader
21:30:40.266 [main] DEBUG org.dcm4che3.imageio.stream.SegmentedInputImageStream -- wasPos 0 end 27930
21:30:40.267 [main] DEBUG org.dcm4che3.imageio.plugins.dcm.DicomImageReader -- Start decompressing frame #1
Cannot load OpenCV native library: no opencv_java in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
21:30:40.272 [main] ERROR org.dcm4che3.opencv.StreamSegment -- Cannot read SegmentedInputImageStream with class com.twelvemonkeys.imageio.stream.BufferedChannelImageInputStream 
java.lang.NullPointerException: Cannot invoke "org.dcm4che3.opencv.StreamSegment.getImageDescriptor()" because "seg" is null
        at org.dcm4che3.opencv.NativeImageReader.getNativeImage(NativeImageReader.java:261)
        at org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:251)
        at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:458)
        at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
        at com.susom.deid.regression.ScrubUtil.imageMD5s(ScrubUtil.java:106)
        at com.susom.deid.regression.ScrubUtil.isDifferent(ScrubUtil.java:78)
        at com.susom.deid.regression.ScrubUtil.main(ScrubUtil.java:50)
```

The code snippet is - 
       ```
DicomImageReader reader = new DicomImageReader(null);
        reader.setInput(ImageIO.createImageInputStream(imageFile));
        ImageReadParam param = reader.getDefaultReadParam();

        Set<String> md5s = new HashSet<>();

        DicomMetaData metadataOrig = reader.getStreamMetadata();
        Attributes attr = metadataOrig.getAttributes();

        int frames = attr.getInt(Tag.NumberOfFrames, 1);

        for (int i = 0; i < frames; i++) {
            BufferedImage bi = reader.read(i);
            ColorModel cm = bi.getColorModel();
            bi = cm.getNumComponents() == 3 ? BufferedImageUtils.convertToIntRGB(bi) : bi;

            // Some rules have widths larger than the actual image to account for variable image sizes
            if (x + w > bi.getWidth()) {
            w = bi.getWidth() - x;
            }
            if (y + h > bi.getHeight()) {
            h = bi.getHeight() - y;
            }

            md5s.add(imageMD5(bi.getSubimage(x, y, w, h)));
        //}
        }
```

**Comment by smitalimaye** [comment]
I could make some progress. I copied the - https://github.com/nroduit/mvn-repo/blob/master/org/weasis/thirdparty/org/opencv/libopencv_java/<weasis.opencv.native.version>/libopencv_java-<weasis.opencv.native.version>-linux-aarch64.so library and renamed it to be libopencv_java.sp ([see here]([url](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-assembly/src/bin/dcm2jpg#L80))

And added this option to my earlier command - -Djava.library.path=<path-to-libopencv_java.sp-file>
Now I am getting another error while loading this native library - 
`Cannot load OpenCV native library: /libopencv_java.so: libopencv_java.so: invalid ELF header`

I think I still haven't found the right library.

**Comment by kathrynalpert** [comment]
I was seeing the same NPE (`seg is null`) on 5.33.1, running on the classpath under Tomcat 9 / JDK 21, and upgrading to 5.35.0 fixed it. 

Claude tells me it's because `StreamSegment` doesn't reflect into `javax.imageio.stream` anymore: In 5.33.1, `getFileStreamSegment` does `getDeclaredField` + `setAccessible`, which is the `InaccessibleObjectException` from the first post; when that gets denied it logs and returns null, and that's where the NPE comes from. In 5.35.0 that's gone and it calls a new `SegmentedInputImageStream.getFile()` instead.

(I didn't bother to identify which release actually changed it, only that 5.33.1 fails and 5.35.0 works.)
