### ISSUE TITLE
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type IApplicationEntityCache with qualifiers @Default   at injection point [BackedAnnotatedField] @Inject private org.dcm4chee.arc.retrieve.scu.impl.CMoveSCUImpl.aeCache

### ISSUE THREAD

**Issue by NieXianjiang** [dcm4che/dcm4che#212]
11:45:06,701 INFO  [org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean] (MSC service thread 1-5) Creating Service {urn:ihe:rad:xdsi-b:2009}ImagingDocumentSource from WSDL: /wsdl/XDS-I.b_ImagingDocumentSource.wsdl
11:45:06,827 INFO  [org.hibernate.dialect.Dialect] (ServerService Thread Pool -- 81) HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
11:45:06,869 INFO  [org.hibernate.envers.boot.internal.EnversServiceImpl] (ServerService Thread Pool -- 81) Envers integration enabled? : true
11:45:07,347 INFO  [org.apache.cxf.endpoint.ServerImpl] (MSC service thread 1-5) Setting the server's publish address to be http://localhost:8080/dcm4chee-arc/xdsi/ImagingDocumentSource
11:45:07,416 INFO  [org.jboss.ws.cxf.deployment] (MSC service thread 1-5) JBWS024074: WSDL published to: file:/E:/SoftwareForWork/wildfly-11.0.0.Final/standalone/data/wsdl/dcm4chee-arc-ear-5.12.0.ear/dcm4chee-arc-retrieve-xdsi-5.12.0.war/wsdl/XDS-I.b_ImagingDocumentSource.wsdl
11:45:07,508 INFO  [org.jboss.as.webservices] (MSC service thread 1-3) WFLYWS0003: Starting service jboss.ws.endpoint."dcm4chee-arc-ear-5.12.0.ear"."dcm4chee-arc-retrieve-xdsi-5.12.0.war"."org.dcm4chee.arc.retrieve.xdsi.ImageDocumentSource"
11:45:07,817 INFO  [org.hibernate.hql.internal.QueryTranslatorFactoryInitiator] (ServerService Thread Pool -- 81) HHH000397: Using ASTQueryTranslatorFactory
11:45:09,671 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.deployment.unit."dcm4chee-arc-ear-5.12.0.ear".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."dcm4chee-arc-ear-5.12.0.ear".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1978)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type IApplicationEntityCache with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.dcm4chee.arc.retrieve.scu.impl.CMoveSCUImpl.aeCache
  at org.dcm4chee.arc.retrieve.scu.impl.CMoveSCUImpl.aeCache(CMoveSCUImpl.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:362)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:137)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:158)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:501)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:59)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

11:45:09,685 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "dcm4chee-arc-ear-5.12.0.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"dcm4chee-arc-ear-5.12.0.ear\".WeldStartService" => "Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type IApplicationEntityCache with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.dcm4chee.arc.retrieve.scu.impl.CMoveSCUImpl.aeCache
  at org.dcm4chee.arc.retrieve.scu.impl.CMoveSCUImpl.aeCache(CMoveSCUImpl.java:0)
"}}
11:45:09,695 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 40) WFLYSRV0010: Deployed "dcm4chee-arc-ear-5.12.0.ear" (runtime-name : "dcm4chee-arc-ear-5.12.0.ear")
11:45:09,700 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."dcm4chee-arc-ear-5.12.0.ear".WeldStartService: Failed to start service

11:45:10,030 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
11:45:10,033 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
11:45:10,033 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
11:45:10,033 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 11.0.0.Final (WildFly Core 3.0.8.Final) started (with errors) in 10201ms - Started 2354 of 2812 services (204 services failed or missing dependencies, 471 services are lazy, passive or on-demand)

**Comment by hczedik** [comment]
Please ask questions in the dcm4che Google Group:
https://groups.google.com/d/forum/dcm4che
