### ISSUE TITLE
hl7rcv error

### ISSUE THREAD

**Issue by mthmn20** [dcm4che/dcm4che#231]
Hi

When I try to use the hl7rcv tool to receive HL7 messages, I always get the following error: 
java.lang.StringIndexOutOfBoundsException: String index out of range: 7
        at java.lang.String.substring(String.java:1963)
        at org.dcm4che3.hl7.HL7Message.makeACK(HL7Message.java:137)
        at org.dcm4che3.hl7.HL7Message.makeACK(HL7Message.java:172)
        at org.dcm4che3.net.hl7.HL7ProtocolHandler.onAccept(HL7ProtocolHandler.java:67)
        at org.dcm4che3.net.TCPListener.listen(TCPListener.java:126)
        at org.dcm4che3.net.TCPListener.access$000(TCPListener.java:56)
        at org.dcm4che3.net.TCPListener$1.run(TCPListener.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Any ideas?

Thanks
Alex

**Comment by vrindanayak** [comment]
- Please recheck the message type, in the MSH segment of the HL7 message, being sent to the hl7rcv tool. 
- The total length of message type should be at least 7 (can be more than 7), eg. `OMI^O23` or `ADT^A28^ADT_A05`. 
Please ask further queries in [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che)
