### ISSUE TITLE
JSONReader.readDataFragment fails to parse "DataFragment"

### ISSUE THREAD

**Issue by lexxoff** [dcm4che/dcm4che#256]
Parsing of the following fragment
```
    "7FE00010":{
        "vr":"OB",
        "DataFragment":[
            {
                "BulkDataURI":"https://main-155feee6-0a0e-11ee-3332-d3c482c02a7c.s3.ca-central-1.amazonaws.com/dicom/full.e01308ed-dad0-40cc-95ff-c360861164de?offset=1904&length=4"
            },
            {
                "BulkDataURI":"https://main-155feee6-0a0e-11ee-3332-d3c482c02a7c.s3.ca-central-1.amazonaws.com/dicom/full.e01308ed-dad0-40cc-95ff-c360861164de?offset=1916&length=648002"
            }
        ]
    }
```

Fails with this exception:

```
javax.json.stream.JsonParsingException: Unexpected "https://main-155feee6-0a0e-11ee-3332-d3c482c02a7c.s3.ca-central-1.amazonaws.com/dicom/full.e01308ed-dad0-40cc-95ff-c360861164de?offset=1904&length=4", expected "InlineBinary" or "BulkDataURI"
	at org.dcm4che3.json.JSONReader.readDataFragment(JSONReader.java:356)
	at org.dcm4che3.json.JSONReader.readDataFragments(JSONReader.java:274)
	at org.dcm4che3.json.JSONReader.readAttribute(JSONReader.java:178)
	at org.dcm4che3.json.JSONReader.doReadDataset(JSONReader.java:141)
	at org.dcm4che3.json.JSONReader.readDataset(JSONReader.java:121)
............
```

**Comment by Jagjit-Thind** [comment]
Hi,

It's a shame this is broken, it was working with 3.3.8 but not since. Is it possible this could be merged asap.

Thanks

**Comment by gofal** [comment]
Could you please point me to DICOM-Standard, where the element "DataFragment" is defined?
Or could it be, that the generated Json is not a valid DicomJson? https://dicom.nema.org/medical/dicom/current/output/chtml/part18/chapter_F.html
