### ISSUE TITLE
Compressor Can't Transcode to JPEG Baseline when BitsStored > 8

### ISSUE THREAD

**Issue by dzelemba** [dcm4che/dcm4che#282]
I'm trying to use the Compressor class to convert a DICOM instance stored in Little Endian Explicit into JPEG Baseline. The source DICOM has BitsStored/BitsAllocated > 8 and there seems to be come code in Dcm2Dcm (i.e. adjustTransferSyntax) the switches the target transfer-syntax in this case to JPEG Extended, but I'm not sure why. Dcm2jpg handles this case just fine and produces a JPEG baseline file.

To reproduce, remove the adjustTransferSyntax code in Dcm2Dcm and run the conversion on any DICOM instance encoded in little endian explicit with BitsStored/Allocated > 8.

Exception:

java.util.concurrent.ExecutionException: com.google.net.rpc3.util.RpcFutureStream$RpcStreamException: <eye3 title='/DicomParserService.Transcode, INTERNAL'/> generic::INTERNAL: javax.imageio.IIOException: Illegal band size: should be 0 < size <= 8
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:497)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:363)
	at org.dcm4che3.imageio.codec.Compressor$CompressedFrame.compress(Compressor.java:324)
	at org.dcm4che3.imageio.codec.Compressor$CompressedFrame.getEncodedLength(Compressor.java:280)
	at org.dcm4che3.io.DicomOutputStream.writeAttribute(DicomOutputStream.java:209)
	at org.dcm4che3.io.DicomOutputStream.writeAttribute(DicomOutputStream.java:187)
	at org.dcm4che3.data.Fragments.writeTo(Fragments.java:149)
	at org.dcm4che3.io.DicomOutputStream.writeAttribute(DicomOutputStream.java:211)
	at org.dcm4che3.io.DicomOutputStream.writeAttribute(DicomOutputStream.java:187)
	at org.dcm4che3.data.Attributes.writeTo(Attributes.java:2794)
	at org.dcm4che3.data.Attributes.writeTo(Attributes.java:2753)
	at org.dcm4che3.io.DicomOutputStream.writeDataset(DicomOutputStream.java:147)

**Comment by gunterze** [comment]
That's a limitation of JPEG Baseline. For bitStored > 8 and <= 12, you may configure to use JPEG Extended (Process 2 & 4) (uid=1.2.840.10008.1.2.4.51)

Please do not open an issue for questions like that, but post them at  https://gro .ups.google.com/forum/#!forum/dcm4che
