### ISSUE TITLE
Problem with building project under Windows

### ISSUE THREAD

**Issue by rrzaripov** [dcm4che/dcm4che#316]
Build master branch failed with next error:
```
...
[ERROR] Error: Could not find or load main class org.jboss.ws.tools.cmd.WSConsume
...
[ERROR] Failed to execute goal org.jboss.ws.plugins:jaxws-tools-maven-plugin:1.2.2.Final:wsconsume (ImagingDocumentSource) on project dcm4che-xdsi: Error while running wsconsume: Process terminated with code 1 -> [Help 1]
...
```
Full build log in [gist](https://gist.github.com/rrzaripov/0dfcaf4b9445de8c3c2003c31b5dfebf).
Some dependencies not installed or another problem?

**Comment by rrzaripov** [comment]
For verify I configured and run build in appveyor, and result same.

**Comment by rrzaripov** [comment]
I think that problem is in latest version of org.jboss.ws.plugins.jaxws-tools-maven-plugin.
Running `mvn -X install` give me next error:

```
[DEBUG] Running command line: java -Djavax.xml.accessExternalDTD=all -Djavax.xml.accessExternalSchema=all -classpath  C:\git\dcm4che\dcm4che-xdsi\target\jaxws-tools\jaxws-tools-maven-plugin-classpath-4627190627476678988.jar org.jboss.ws.tools.cmd.WSConsume -k -p org.dcm4che3.xdsi -w /wsdl/XDS-I.b_ImagingDocumentSource.wsdl -d UTF-8 -o C:\git\dcm4che\dcm4che-xdsi\target\classes -s C:\git\dcm4che\dcm4che-xdsi\target\generated-sources\wsconsume -t 2.2 -e -n C:\git\dcm4che\dcm4che-xdsi/src/main/resources/wsdl/XDS-I.b_ImagingDocumentSource.wsdl 
[ERROR] Error: Could not find or load main class org.jboss.ws.tools.cmd.WSConsume
```

With version 1.2.1.Final build is success, but needed gnu.getopt.java-getopt package:

```
[DEBUG] Running command line: java -Djavax.xml.accessExternalDTD=all -Djavax.xml.accessExternalSchema=all -classpath  C:\git\dcm4che\dcm4che-xdsi\target\jaxws-tools\jaxws-tools-maven-plugin-classpath-8366487579523538473.jar org.jboss.ws.tools.cmd.WSConsume -k -p org.dcm4che3.xdsi -w /wsdl/XDS-I.b_ImagingDocumentSource.wsdl -d UTF-8 -o C:\git\dcm4che\dcm4che-xdsi\target\classes -s C:\git\dcm4che\dcm4che-xdsi\target\generated-sources\wsconsume -t 2.2 -e -n C:\git\dcm4che\dcm4che-xdsi/src/main/resources/wsdl/XDS-I.b_ImagingDocumentSource.wsdl 
[ERROR] Exception in thread "main" java.lang.NoClassDefFoundError: gnu/getopt/LongOpt
[ERROR] 	at org.jboss.ws.tools.cmd.WSConsume.parseArguments(WSConsume.java:114)
[ERROR] 	at org.jboss.ws.tools.cmd.WSConsume.mainInternal(WSConsume.java:107)
[ERROR] 	at org.jboss.ws.tools.cmd.WSConsume.main(WSConsume.java:96)
[ERROR] Caused by: java.lang.ClassNotFoundException: gnu.getopt.LongOpt
[ERROR] 	at java.net.URLClassLoader.findClass(Unknown Source)
[ERROR] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[ERROR] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[ERROR] 	... 3 more
```
I'm not found any idea for build dcm4che with 1.2.2.Final under Windows. Maybe anyone have another solution?
