### ISSUE TITLE
NullPointerException when reading certain images (5.13.0)

### ISSUE THREAD

**Issue by er453r** [dcm4che/dcm4che#318]
Since version `5.13.0` (`5.12.0` works ok) some DICOMs (attached one of them) throw when reading:

```
java.lang.NullPointerException: null
	at org.dcm4che3.opencv.NativeImageReader.getNativeImage(NativeImageReader.java:257) ~[dcm4che-imageio-opencv-5.13.2.jar:na]
	at org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:252) ~[dcm4che-imageio-opencv-5.13.2.jar:na]
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:452) ~[dcm4che-imageio-5.13.2.jar:5.13.2]
```

From what I've managed to debug this is related to the MR https://github.com/dcm4che/dcm4che/pull/247 and somewhat to this MR https://github.com/dcm4che/dcm4che/pull/226 

[0012.zip](https://github.com/dcm4che/dcm4che/files/2184691/0012.zip)

**Comment by gunterze** [comment]
I cannot reproduce the failure with with current master (5.13.3):
```
$ dcm2jpg /tmp/0012.DCM --frame 2 /tmp/0012.jpeg
15:27:07,172 DEBUG - Decompressor: org.dcm4che3.opencv.NativeImageReader
15:27:07,175 DEBUG - wasPos 0 end 9223372036854775807
15:27:07,176 DEBUG - Start decompressing frame #2
15:27:07,194 DEBUG - Finished decompressing frame #2
/tmp/0012.DCM -> /tmp/0012.jpeg
```

**Comment by er453r** [comment]
Ok, I've investigated further (using your example). The difference is I'm reading my images directly from memory, so if you substitute here https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-dcm2jpg/src/main/java/org/dcm4che3/tool/dcm2jpg/Dcm2Jpg.java#L359 

```java
ImageInputStream iis = ImageIO.createImageInputStream(src);
```

with

```java
byte[] data = Files.readAllBytes(Paths.get(src.getAbsolutePath())); // read file to byte array
ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(data); // convert memory to stream
ImageInputStream iis = ImageIO.createImageInputStream(byteArrayInputStream); // use this as input
```
Than it will fail :smile:

**Comment by nroduit** [comment]
I publish a [PR](https://github.com/dcm4che/dcm4che/pull/330) to fix the use of FileCacheImageInputStream and MemoryCacheImageInputStream (currently only FileImageInputStream is  supported).

However, I would not recommend using the code above to read image in memory because it will by default write a temp file with [InputStreamImageInputStreamSpi](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/com/sun/imageio/spi/InputStreamImageInputStreamSpi.java#L61).
You can add `ImageIO.setUseCache(false);` at the beggining to use MemoryCacheImageInputStream but it will required to duplicate the array in memory (image part).

The best solution (works in the current version) is without InputStreamImageInputStreamSpi:
```java
        byte[] data = Files.readAllBytes(Paths.get(src.getAbsolutePath())); // read file to byte array
        ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(data); // convert memory to stream
        DicomInputStream dicomStream = new DicomInputStream(byteArrayInputStream);
        try {
            imageReader.setInput(dicomStream);
            BufferedImage bi =  imageReader.read(frame-1, readParam());
            bi = convert(bi);
            dest.delete();
            ImageOutputStream ios = ImageIO.createImageOutputStream(dest);
            try {
                writeImage(ios, bi);
            } finally {
                try { ios.close(); } catch (IOException ignore) {}
            }
        } finally {
            try { dicomStream.close(); } catch (IOException ignore) {}
        }
```
