### ISSUE TITLE
compress error

### ISSUE THREAD

**Issue by wanghailin91** [dcm4che/dcm4che#361]
javax.imageio.IIOException: Illegal band size: should be 0 < size <= 8
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:494)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:360)
	at org.dcm4che3.imageio.codec.Transcoder.compressFrame(Transcoder.java:540)
	at org.dcm4che3.imageio.codec.Transcoder.compressPixelData(Transcoder.java:453)
	at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:394)
	at org.dcm4che3.imageio.codec.Transcoder.access$2(Transcoder.java:388)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:351)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:533)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:335)
	at org.dcm4che3.imageio.codec.TranscoderTest.test(TranscoderTest.java:199)
	at org.dcm4che3.imageio.codec.TranscoderTest.testCompressPerPixelRGB(TranscoderTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
--------------------------------------------------------------------------------------------------------------
09:05:26,506 WARN  - No preferred Writer com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageWriter for format: jpeg - use com.sun.imageio.plugins.jpeg.JPEGImageWriter
09:05:26,507 DEBUG - Compressor: com.sun.imageio.plugins.jpeg.JPEGImageWriter

**Comment by hczedik** [comment]
Hello @wanghailin91,

can you please specify what calls exactly you are doing to compress data. And can you please provide the data itself (anonymized)?
Thanks.

**Comment by wanghailin91** [comment]
the problem is solved, currently for compression, It requires to use a 32-bit Java Runtime on Windows. Install plug-in:jai_imageio-1_0_01-lib-windows-i586-jdk.exe
Thanks.
