### ISSUE TITLE
dcm2jpg throws EOFException when converting deflated explicit VR little endian file

### ISSUE THREAD

**Issue by KarlSjostrand** [dcm4che/dcm4che#42]
Platform: macOS Sierra 10.12.3
dcm4che version: 3.3.8

To reproduce: convert file with TS explicit VR little endian to deflated using `dcm2dcm -t 1.2.840.10008.1.2.1.99 file.dcm file_defl.dcm`. Create jpeg file using `dcm2jpg file_defl.dcm file.jpg`

Result:
```
Failed to convert file_defl.dcm: null
java.io.EOFException
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:353)
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:373)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.readRaster(DicomImageReader.java:295)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:342)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.readImage(Dcm2Jpg.java:381)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.convert(Dcm2Jpg.java:360)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.mconvert(Dcm2Jpg.java:345)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.main(Dcm2Jpg.java:314)
```

Does dcm4che's DicomImageReader not support deflated datasets?

**Comment by william00179** [comment]
Just some overdue follow up on this. Per the header comments in the DicomImageReader, we can pass a few different types into the setInput() function, those being an InputStream, DicomMetaData or ImageInputStream. 

> Supports compressed and uncompressed images from a DicomMetaData object, an InputStream/DicomInputStream or an ImageInputStream.
>  * For ImageInputStream, the access supports random/out of order reading from the input for everything except deflated streams.
>  * For InputStream type data, only sequential access to images is supported, including deflated.
>  * For DicomMetaData, random access is fully supported, and can have been read from a deflated stream.

So I suspect you're passing an ImageInputStream which the DicomImageReader is not able to inflate. 

Try pass in a DicomInputStream and it will inflate the InputStream for you.
