### ISSUE TITLE
No Writer for format: jpeg-ls-cv registered

### ISSUE THREAD

**Issue by wmxj** [dcm4che/dcm4che#420]
1.The tool used:dcm2dcm 

2:Question: 
Dcm2Dcm main = new Dcm2Dcm();													    		            main.setTransferSyntax(UID.JPEGLSLossless);

Method mtranscode often can be used normally when the system starts, but after running for a period of time will be wrong：

java.lang.RuntimeException: No Writer for format: jpeg-ls-cv registered
        at org.dcm4che3.imageio.codec.ImageWriterFactory.getImageWriterFromImageIOServiceRegistry(ImageWriterFactory.java:243)
        at org.dcm4che3.imageio.codec.ImageWriterFactory.getImageWriter(ImageWriterFactory.java:237)
        at org.dcm4che3.imageio.codec.Transcoder.initCompressor(Transcoder.java:284)
        at org.dcm4che3.imageio.codec.Transcoder.setDestinationTransferSyntax(Transcoder.java:251)
        at Dcm2Dcm.transcodeWithTranscoder(Dcm2Dcm.java:332)
        at Dcm2Dcm.transcode(Dcm2Dcm.java:274)
        at Dcm2Dcm.mtranscode(Dcm2Dcm.java:262)

3: JDK1.8 32 bits and 64 bits have been tried.

**Comment by gunterze** [comment]
Check if the native lib for opencv for your OS and cpu arch is the the library path. Post questions to the dcm4che Google group https://groups.google.com/forum/#!forum/dcm4che .
