### ISSUE TITLE
jpg2dcm fails with OpenJDK 11

### ISSUE THREAD

**Issue by alanbirtles** [dcm4che/dcm4che#444]
Since upgrading to OpenJDK11 on Ubuntu 18.04 jpg2dcm fails with the following stack trace:

<pre>Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/FileTypeMap
	at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm$FileType.valueOf(Jpg2Dcm.java:303)
	at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.toFileType(Jpg2Dcm.java:192)
	at org.dcm4che3.tool.jpg2dcm.Jpg2Dcm.main(Jpg2Dcm.java:120)
Caused by: java.lang.ClassNotFoundException: javax.activation.FileTypeMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more
</pre>

Tested with 5.16.2

**To Reproduce**
1. update OpenJDK package to 11.0.2+9-3ubuntu1~18.04.3 (previous working version was 10.0.2+13-1ubuntu0.18.04.4)
2. Run ```/jpg2dcm 'in.jpg' 'jpeg.dcm'```

**Comment by alanbirtles** [comment]
fix verified on Ubuntu 18.04
