### ISSUE TITLE
timeout for writeDIMSE

### ISSUE THREAD

**Issue by mbakhoff** [dcm4che/dcm4che#532]
Currently c-store (and many other operations) is affected by idle timeouts and response timeouts. However it seems neither apply for the sending of the actual request itself and there is no way to set a timeout for that.

Association::invoke:
```
    public void invoke(PresentationContext pc, Attributes cmd,
                       DataWriter data, DimseRSPHandler rspHandler, int rspTimeout, boolean stopOnPending)
            throws IOException, InterruptedException {
        stopTimeout();
        checkException();
        rspHandler.setPC(pc);
        addDimseRSPHandler(rspHandler);
        encoder.writeDIMSE(pc, cmd, data); // <- no way to set timeout
        startTimeout(rspHandler.getMessageID(), rspTimeout, stopOnPending);
    }
```

I discovered the issue when a dcm4chee-arc instance stopped processing c-move requests because its thread pool was overfilled with stuck associations to a buggy remote server. 

Sample stack with dcm4chee-arc-light 5.16.2:
```
java.lang.Thread.State: RUNNABLE
    at java.net.SocketOutputStream.socketWrite0(java.base@11.0.3/Native Method)
    at java.net.SocketOutputStream.socketWrite(java.base@11.0.3/SocketOutputStream.java:110)
    at java.net.SocketOutputStream.write(java.base@11.0.3/SocketOutputStream.java:150)
    at org.dcm4che3.net.PDUEncoder.writePDU(PDUEncoder.java:128)
    - locked <0x00000007148042a0> (a org.dcm4che3.net.PDUEncoder)
    at org.dcm4che3.net.PDUEncoder.writePDataTF(PDUEncoder.java:394)
    at org.dcm4che3.net.Association.doWritePDataTF(Association.java:695)
    at org.dcm4che3.net.State$4.writePDataTF(State.java:113)
    at org.dcm4che3.net.Association.writePDataTF(Association.java:691)
    at org.dcm4che3.net.PDUEncoder.flushPDataTF(PDUEncoder.java:371)
    at org.dcm4che3.net.PDUEncoder.write(PDUEncoder.java:318)
    at org.dcm4che3.io.DicomOutputStream.write(DicomOutputStream.java:114)
    at org.dcm4che3.util.StreamUtils.copy(StreamUtils.java:111)
    at org.dcm4che3.imageio.codec.Transcoder.copyPixelData(Transcoder.java:463)
    at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:431)
    at org.dcm4che3.imageio.codec.Transcoder.access$200(Transcoder.java:70)
    at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:383)
    at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:534)
    at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:362)
    at org.dcm4chee.arc.store.scu.impl.TranscoderDataWriter.writeTo(TranscoderDataWriter.java:69)
    at org.dcm4che3.net.PDUEncoder.writeDIMSE(PDUEncoder.java:437)
    - locked <0x0000000714804540> (a java.lang.Object)
    at org.dcm4che3.net.Association.invoke(Association.java:1228)
    at org.dcm4che3.net.Association.invoke(Association.java:1218)
    at org.dcm4che3.net.Association.cstore(Association.java:901)
    at org.dcm4chee.arc.store.scu.impl.RetrieveTaskImpl.store(RetrieveTaskImpl.java:174)
    at org.dcm4chee.arc.store.scu.impl.RetrieveTaskImpl.run(RetrieveTaskImpl.java:130)
    at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105)
    at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.3/Executors.java:515)
    at java.util.concurrent.FutureTask.run(java.base@11.0.3/FutureTask.java:264)
    at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.3/ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.3/ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)
    at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
    at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:85)
```

Would it be possible to add a timeout for sending the c-store request? 

Note that the response timeout actually covered the writeDIMSE in the past, but was changed to fix https://github.com/dcm4che/dcm4che/issues/344

**Comment by gunterze** [comment]
Made configurable by
```java
public class Connection implements Serializable {
...
    /**
     * Timeout in ms for sending other DIMSE RQs than C STORE-RQs.
     *
     * @return Timeout in ms or {@code 0} (= no timeout).
     */
    public int getSendTimeout() {
        return sendTimeout;
    }

    /**
     * Timeout in ms for sending other DIMSE RQs than C-STORE RQs.
     *
     * @param timeout Timeout in ms or {@code 0} (= no timeout).
     */
    public void setSendTimeout(int timeout) {
        this.sendTimeout = timeout;
    }

    /**
     * Timeout in ms for sending C-STORE RQs.
     *
     * @return Timeout in ms or {@code 0} (= no timeout).
     */
    public int getStoreTimeout() {
        return storeTimeout;
    }

    /**
     * Timeout in ms for sending C-STORE RQs.
     *
     * @param timeout Timeout in ms or {@code 0} (= no timeout).
     */
    public void setStoreTimeout(int timeout) {
        this.storeTimeout = timeout;
    }

```

**Comment by mbakhoff** [comment]
Thank you! That's exactly what was needed :)
