### ISSUE TITLE
Dcm2jpg on 64bit JRE

### ISSUE THREAD

**Issue by TCM5** [dcm4che/dcm4che#610]
**Describe the bug**
It's not possible to run the DCM 2 JPG converter using a 64 bit JRE. I need to convert an .RVG file to JPEG and it fails everytime with this error:

```
avax.imageio.IIOException: codecLib error
	at com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader.getInfoImage(CLibJPEGImageReader.java:207)
	at com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader.getImageTypes(CLibJPEGImageReader.java:274)
	at java.desktop/javax.imageio.ImageReader.getRawImageType(ImageReader.java:680)
	at com.sun.media.imageioimpl.plugins.clib.CLibImageReader.read(CLibImageReader.java:571)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:331)
	at com.waymotion.clinicapatrao.services.model.test.main(test.java:33)
Caused by: java.lang.UnsatisfiedLinkError: com.sun.medialib.codec.jpeg.Decoder.njpeg_decode_init(Ljava/lang/Object;)J
	at com.sun.medialib.codec.jpeg.Decoder.njpeg_decode_init(Native Method)
	at com.sun.medialib.codec.jpeg.Decoder.<init>(Decoder.java:58)
	at com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader.getInfoImage(CLibJPEGImageReader.java:199)
	... 5 more
```

**To Reproduce**
1. Load an .RVG file with Dcm2Jpg class
2. run convert method

**Expected behavior**
Convert to a bytearray without problems

**Desktop (please complete the following information):**
 - OS: Win10, runing java app within java 8 64bit

**Comment by gunterze** [comment]
Since 5.13.0 `com.sun.media.imageioimpl.plugins.clib.CLibImageReader` is no longer used by default  for decompressing JPEG compressed DICOM Pixeldata. Since 5.13.0  `org.dcm4che3.opencv.NativeImageReader`  is used  which native parts (opencv_java.dll) are also provided for win-x86_64

s. [ImageReaderFactory.properties](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-imageio/src/main/resources/org/dcm4che3/imageio/codec/ImageReaderFactory.properties)

**Comment by TCM5** [comment]
Oh.. I didn't know you guys made that change, that's great!
I was still using de 2.0.25 version bahhhh, sorry for asking this.
