### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path

### ISSUE THREAD

**Issue by hczedik** [dcm4che/dcm4che#628]
**Describe the bug**
When starting the dcm2dcm.bat command on Windows 10 I get the following error:

```
16:29:12,385 DEBUG - Decompressor: org.dcm4che3.opencv.NativeImageReader
Exception in thread "main" java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.opencv.osgi.OpenCVNativeLoader.init(OpenCVNativeLoader.java:17)
        at org.dcm4che3.opencv.StreamSegment.<clinit>(StreamSegment.java:76)
        at org.dcm4che3.opencv.NativeImageReader.getNativeImage(NativeImageReader.java:260)
        at org.dcm4che3.opencv.NativeImageReader.read(NativeImageReader.java:251)
        at org.dcm4che3.imageio.codec.Transcoder.decompressFrame(Transcoder.java:604)
        at org.dcm4che3.imageio.codec.Transcoder.decompressPixelData(Transcoder.java:451)
        at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:432)
        at org.dcm4che3.imageio.codec.Transcoder.access$300(Transcoder.java:70)
        at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:387)
        at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:534)
        at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:366)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcodeWithTranscoder(Dcm2Dcm.java:411)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcode(Dcm2Dcm.java:350)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:341)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:318)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.main(Dcm2Dcm.java:290)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 5.20.0

**Additional context**
This is a regression caused by the fix for #550.

**Comment by geha** [comment]
This reintroduces the error described in #550 regarding spaces in the path where the dcm4che binaries are located.

The actual reason for the described problem lies within the line above your change:
https://github.com/dcm4che/dcm4che/blob/81eaa19d042468424bac59077f77121eb8ca0085/dcm4che-assembly/src/bin/dcm2jpg.bat#L61 sets `%OS%` to `win-x86_64 ` (mind the space at the end) on a 64-bit system when running with Java 8 or lower.

This in turn leads to a library path that contains a space at the end, which is invalid when written in quotes: e.g. `-Djava.library.path="E:\temp\dcm4che-5.20.0\bin\..\lib\win-x86_64 "` (explicit space within quotes)

The reason why your patch worked is because it omits the quotes around the library path variable: e.g. `-Djava.library.path=E:\temp\dcm4che-5.20.0\bin\..\lib\win-x86_64 ` (space not within quotes)
In this case the space at the end will just be ignored by the command line. 

Unfortunately this is not compatible if there are spaces in the execution path (which sadly are allowed on Windows 😞)
`"E:\temp\dcm4che 5.20.0\bin\dcm2jpg.bat" test.dcm .` (space in directory name)
causes the error:
```Error: Could not find or load main class 5.20.0\bin\..\lib\win-x86_64```

I submitted #613 which should solve your initial problem as well as compatibility issue with newer Java versions.

**Comment by geha** [comment]
Sorry if I wasn't specific enough about the contents of my PR. The changes introduced in #629 should be reverted in order to allow spaces in `%DCM4CHE_HOME%` again.

I could also submit another PR with the necessary changes if that is easier for you, instead of a revert.

**Comment by gunterze** [comment]
Yes, please provide another PR. It's some effort for me to test it on Windows.

**Comment by hczedik** [comment]
Thanks @geha for finding the root cause of this problem!

**Comment by geha** [comment]
> Yes, please provide another PR. It's some effort for me to test it on Windows.

Done with #644.
