### ISSUE TITLE
Transcoder: verification of JPEG Lossless and JPEG-LS compression of signed pixel data fails with java.lang.ClassCastException

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#646]
```
Failed to transcode /home/gunter/testdata/signedrangeimages/test12signedPositiveNW.dcm: class java.awt.image.DataBufferUShort cannot be cast to class java.awt.image.DataBufferShort (java.awt.image.DataBufferUShort and java.awt.image.DataBufferShort are in module java.desktop of loader 'bootstrap')
java.lang.ClassCastException: class java.awt.image.DataBufferUShort cannot be cast to class java.awt.image.DataBufferShort (java.awt.image.DataBufferUShort and java.awt.image.DataBufferShort are in module java.desktop of loader 'bootstrap')
	at org.dcm4che3.imageio.codec.Transcoder.maxDiff(Transcoder.java:899)
	at org.dcm4che3.imageio.codec.Transcoder.verify(Transcoder.java:852)
	at org.dcm4che3.imageio.codec.Transcoder.compressFrame(Transcoder.java:642)
	at org.dcm4che3.imageio.codec.Transcoder.compressPixelData(Transcoder.java:492)
	at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:429)
	at org.dcm4che3.imageio.codec.Transcoder.access$300(Transcoder.java:70)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:387)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:534)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:366)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcodeWithTranscoder(Dcm2Dcm.java:411)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcode(Dcm2Dcm.java:350)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:341)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:329)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:318)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.main(Dcm2Dcm.java:290)
```
Caused by return of `java.awt.image.UShortDataBuffer` by `org.dcm4che3.opencv.NativeJPEGImageWriter` and `org.dcm4che3.opencv.NativeJLSImageWriter` independently if the pixel values are signed or unsigned

**Comment by nroduit** [comment]
Currently, it's not in the APIs but yes theoretically it is possible for JPEG200 and JPEG-LS. However, the benefit is not significant (at least for JPEG-LS).

I will see if it would be possible to add a parameter to force the number of bits and by default during transcoding keep the same number of bits.
