### ISSUE TITLE
json2dcm java.lang.NullPointerException while changing tag 00020003

### ISSUE THREAD

**Issue by jimOnAir** [dcm4che/dcm4che#679]
Hello. I'm trying to change tags 00020003, 00080018 and getting java.lang.NullPointerException
my json file is:
```json
{
  "00020003": {
    "vr": "UI",
    "Value": ["1.3.6.1.4.1.222222.1.4.190195020.5488.1557087327.279.6.5.4.3.4"]
  },
  "00080018": {
    "vr": "UI",
    "Value": ["1.3.6.1.4.1.222222.1.4.190195020.5488.1557087327.279.6.5.4.3.4"]
  }
}
```
and sample dcm:
[7BAF1D3F.zip](https://github.com/dcm4che/dcm4che/files/4220433/7BAF1D3F.zip)

the command is:
```console
$ json2dcm -i 7BAF1D3F -j patch.json -o patched/7BAF1D3F
json2dcm: null
java.lang.NullPointerException
        at org.dcm4che3.io.DicomOutputStream.switchTransferSyntax(DicomOutputStream.java:150)
        at org.dcm4che3.io.DicomOutputStream.writeDataset(DicomOutputStream.java:137)
        at org.dcm4che3.tool.json2dcm.Json2Dcm.writeTo(Json2Dcm.java:340)
        at org.dcm4che3.tool.json2dcm.Json2Dcm.main(Json2Dcm.java:273)

```
json2dcm version

```console
$ /opt/dcm4che-toolkit/bin/json2dcm -V
json2dcm: 5.21.0
```

**Comment by gunterze** [comment]
Workaround: Include all File Meta Information attributes in patch.json
