### ISSUE TITLE
dcm2dcm: -q / -Q options cannot be used

### ISSUE THREAD

**Issue by r1b** [dcm4che/dcm4che#735]
**Describe the bug**
An IllegalArgumentException is thrown when any value is passed to the -q or -Q options in dcm2dcm

**To Reproduce**

```
# All of these throw IllegalArgumentException
dcm2dcm --jpeg -q 80 foo.dcm bar.dcm
dcm2dcm --jpeg -q 0.8 foo.dcm bar.dcm
dcm2dcm --j2ki -Q 20 foo.dcm bar.dcm
dcm2dcm --j2ki -q 0.2 foo.dcm bar.dcm
```

**Expected behavior**
I would expect these options to be parsed and applied.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS v10.15.4
 - Browser N/A
 - Version dcm2dcm: 5.22.1

**Additional context**
I'm assuming that for `-q <n>` `n` is quality / 100 and for `-Q <m>` `m` is rate / 100 but it's not clear to me from the available documentation.

**Comment by r1b** [comment]
Here is a stack trace for `-q`:

```
Jun 04, 2020 4:17:33 PM org.opencv.osgi.OpenCVNativeLoader init
INFO: Successfully loaded OpenCV native library.
16:17:33,313 DEBUG - Compressor: org.dcm4che3.opencv.NativeJPEGImageWriter
Failed to transcode foo.test.dcm: null
java.lang.IllegalArgumentException
        at org.dcm4che3.util.Property.setAt(Property.java:152)
        at org.dcm4che3.imageio.codec.Transcoder.setCompressParams(Transcoder.java:332)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcodeWithTranscoder(Dcm2Dcm.java:409)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcode(Dcm2Dcm.java:350)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:341)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:318)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.main(Dcm2Dcm.java:290)
```

And for `-Q`:

```
Failed to transcode foo.test.dcm: org.dcm4che3.opencv.J2kImageWriteParam.setEncodingRate(double)
java.lang.IllegalArgumentException: org.dcm4che3.opencv.J2kImageWriteParam.setEncodingRate(double)
        at org.dcm4che3.util.Property.setAt(Property.java:148)
        at org.dcm4che3.imageio.codec.Transcoder.setCompressParams(Transcoder.java:332)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcodeWithTranscoder(Dcm2Dcm.java:409)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcode(Dcm2Dcm.java:350)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:341)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:318)
        at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.main(Dcm2Dcm.java:290)
```

**Comment by r1b** [comment]
It's also not clear to me that `-Q` corresponds to any J2KWriteParam - the only available parameter is a compression ratio:

https://github.com/dcm4che/dcm4che/blob/8199ee5eeaf7fe24f8d7541b48c918606c3bbb34/dcm4che-imageio-opencv/src/main/java/org/dcm4che3/opencv/J2kImageWriteParam.java#L64

but I am not sure *shrug*

**Comment by gunterze** [comment]
**Attention:**
Option `-Q` changed to:
```
 -Q <compression>             compression factor (5-100) of JPEG 2000
                              Lossy compression
```

**Comment by r1b** [comment]
Thank you!
