### ISSUE TITLE
hl7rcv fail to read message start with BOM or wraped with MLP

### ISSUE THREAD

**Issue by auziel** [dcm4che/dcm4che#779]
**Describe the bug**
If hl7 message start with [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) and wrapped with [MLP](https://healthstandards.com/blog/2007/05/02/hl7-mlp-minimum-layer-protocol-defined/) hl7rcv fail with exception

```
Exception in thread "pool-1-thread-17" java.lang.StringIndexOutOfBoundsException: begin 4, end 7, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
	at java.base/java.lang.String.substring(String.java:1902)
	at org.dcm4che3.hl7.HL7Message.makeACK(HL7Message.java:137)
	at org.dcm4che3.hl7.HL7Message.makeACK(HL7Message.java:172)
	at org.dcm4che3.net.hl7.HL7ProtocolHandler$HL7Receiver.run(HL7ProtocolHandler.java:95)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
**To Reproduce**
1. create an hl7 message which start with BOM characters or wrapped with MLP characters
2. start hl7rcv
3. using hl7snd send the message 

In the attached zip file you can find the hl7 "problematic" message, and a full output of hl7snd and hl7rcv.
[Archive.zip](https://github.com/dcm4che/dcm4che/files/5137129/Archive.zip)

**Expected behavior**
hl7rcv should be able to receive the message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**
Using hl7 utilities from dcm4che v5.15.1

**Comment by auziel** [comment]
After some more investigation I figure out that since the sender is adding BOM to the beginning to the message and append x0A to the end. The bytes stream doesn't meet the messages wrapper as defined by MLLP.
