### ISSUE TITLE
Findscu by date and time returns IllegalArgumentException

### ISSUE THREAD

**Issue by danijc3** [dcm4che/dcm4che#844]
Since version 5.22.1, the findscu exe is returning illegal argument exceptions on date time filtering, eg:

findscu.bat -b **AET** -L STUDY -c **AET**@**HOST**:**PORT** -m StudyDate=**_20201130_**-_**20201130**_ -m StudyTime=_**080100**_-_**080159**_ -r SpecificCharacterSet -r StudyTime -r AccessionNumber -r StudyDescription -r PatientName -r PatientSex -r StudyInstanceUID -r StudyID -r NumberOfStudyRelatedSeries -r NumberOfStudyRelatedInstances -r ModalitiesInStudy -r PatientID -r 0020000d -r 00100030
findscu: 20201130-20201130
java.lang.IllegalArgumentException: 20201130-20201130
        at org.dcm4che3.tool.common.CLIUtils.toTag(CLIUtils.java:689)
        at org.dcm4che3.tool.common.CLIUtils.toTags(CLIUtils.java:679)
        at org.dcm4che3.tool.common.CLIUtils.addAttributes(CLIUtils.java:807)
        at org.dcm4che3.tool.findscu.FindSCU.configureKeys(FindSCU.java:423)
        at org.dcm4che3.tool.findscu.FindSCU.main(FindSCU.java:354)

Such behavior doesn't happen on version 5.22.1.
Tested on version 5.22.4 and 5.22.6.
As for [issue 740](https://github.com/dcm4che/dcm4che/issues/740#issue-637686733), findscu is one of the affected bins by a bug, which is indicated to have been solved on release 5.22.3.

Best regards,
Daniel Carvalho

**Comment by gunterze** [comment]
Not reproducible with linux bash.
```
$ findscu -c TEST@test-ng:11112 -m StudyDate=20201130-20201130 -m StudyTime=080100-080159 -r SpecificCharacterSet -r StudyTime -r AccessionNumber -r StudyDescription -r PatientName -r PatientSex -r StudyInstanceUID -r StudyID -r NumberOfStudyRelatedSeries -r NumberOfStudyRelatedInstances -r ModalitiesInStudy -r PatientID -r 0020000d -r 00100030
15:30:18,414 INFO  - Initiate connection from 0.0.0.0/0.0.0.0:0 to test-ng:11112
15:30:18,423 INFO  - Established connection Socket[addr=test-ng/192.168.2.145,port=11112,localport=39989]
15:30:18,430 DEBUG - /192.168.2.131:39989->test-ng/192.168.2.145:11112(1): enter state: Sta4 - Awaiting transport connection opening to complete
15:30:18,431 INFO  - FINDSCU->TEST(1) << A-ASSOCIATE-RQ
15:30:18,443 DEBUG - A-ASSOCIATE-RQ[
  calledAET: TEST
  callingAET: FINDSCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 1.2.40.0.13.1.3
  implVersionName: dcm4che-5.23.0
  maxPDULength: 16378
  maxOpsInvoked/maxOpsPerformed: 0/0
  PresentationContext[id: 1
    as: 1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
    ts: 1.2.840.10008.1.2.1 - Explicit VR Little Endian
    ts: 1.2.840.10008.1.2.2 - Explicit VR Big Endian (Retired)
  ]
]
15:30:18,443 DEBUG - FINDSCU->TEST(1): enter state: Sta5 - Awaiting A-ASSOCIATE-AC or A-ASSOCIATE-RJ PDU
15:30:18,447 INFO  - FINDSCU->TEST(1) >> A-ASSOCIATE-AC
15:30:18,447 DEBUG - A-ASSOCIATE-AC[
  calledAET: TEST
  callingAET: FINDSCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 1.2.40.0.13.1.3
  implVersionName: dcm4che-5.23.0
  maxPDULength: 16378
  maxOpsInvoked/maxOpsPerformed: 0/0
  PresentationContext[id: 1
    result: 0 - acceptance
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
  ]
]
15:30:18,447 DEBUG - FINDSCU->TEST(1): enter state: Sta6 - Association established and ready for data transfer
15:30:18,450 INFO  - FINDSCU->TEST(1) << 1:C-FIND-RQ[pcid=1, prior=0
  cuid=1.2.840.10008.5.1.4.1.2.2.1 - Study Root Query/Retrieve Information Model - FIND
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
15:30:18,473 DEBUG - FINDSCU->TEST(1) << 1:C-FIND-RQ Command:
(0000,0002) UI [1.2.840.10008.5.1.4.1.2.2.1] AffectedSOPClassUID
(0000,0100) US [32] CommandField
(0000,0110) US [1] MessageID
(0000,0700) US [0] Priority
(0000,0800) US [0] CommandDataSetType

15:30:18,475 DEBUG - FINDSCU->TEST(1) << 1:C-FIND-RQ Dataset:
(0008,0005) CS [] SpecificCharacterSet
(0008,0020) DA [20201130-20201130] StudyDate
(0008,0030) TM [080100-080159] StudyTime
(0008,0050) SH [] AccessionNumber
(0008,0052) CS [STUDY] QueryRetrieveLevel
(0008,0061) CS [] ModalitiesInStudy
(0008,1030) LO [] StudyDescription
(0010,0010) PN [] PatientName
(0010,0020) LO [] PatientID
(0010,0030) DA [] PatientBirthDate
(0010,0040) CS [] PatientSex
(0020,000D) UI [] StudyInstanceUID
(0020,0010) SH [] StudyID
(0020,1206) IS [] NumberOfStudyRelatedSeries
(0020,1208) IS [] NumberOfStudyRelatedInstances
...
```
