### ISSUE TITLE
java.lang.NoSuchMethodError: 'long org.dcm4che3.util.StringUtils.parseIS(java.lang.String)'

### ISSUE THREAD

**Issue by rcsnogm** [dcm4che/dcm4che#848]
**Describe the bug**
Calling Xml2Dcm.xml2DiconByteArray fails with this error:
java.lang.NoSuchMethodError: 'long org.dcm4che3.util.StringUtils.parseIS(java.lang.String)'
	at org.dcm4che3.data.BinaryValueType.toBytes(BinaryValueType.java:439) ~[dcm4che-core-5.22.6.jar:5.22.6]
	at org.dcm4che3.data.BinaryValueType.toValue(BinaryValueType.java:636) ~[dcm4che-core-5.22.6.jar:5.22.6]
	at org.dcm4che3.data.BinaryValueType.toValue(BinaryValueType.java:645) ~[dcm4che-core-5.22.6.jar:5.22.6]
	at org.dcm4che3.data.VR.toValue(VR.java:365) ~[dcm4che-core-5.22.6.jar:5.22.6]
	at org.dcm4che3.data.Attributes.setString(Attributes.java:1961) ~[dcm4che-core-5.22.6.jar:5.22.6]
	at org.dcm4che3.io.ContentHandlerAdapter.endDicomAttribute(ContentHandlerAdapter.java:354) ~[dcm4che-core-5.22.6.jar:5.22.6]
	at org.dcm4che3.io.ContentHandlerAdapter.endElement(ContentHandlerAdapter.java:274) ~[dcm4che-core-5.22.6.jar:5.22.6]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324) ~[?:?]
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:197) ~[?:?]
	at org.dcm4che3.tool.xml2dcm.Xml2Dcm.parseXML(Xml2Dcm.java:145) ~[classes/:?]
	at org.dcm4che3.tool.xml2dcm.Xml2Dcm.mergeXML(Xml2Dcm.java:135) ~[classes/:?]
	at org.dcm4che3.tool.xml2dcm.Xml2Dcm.xml2DicomOutputStream(Xml2Dcm.java:116) ~[classes/:?]
	at org.dcm4che3.tool.xml2dcm.Xml2Dcm.xml2DicomByteArray(Xml2Dcm.java:97) ~[classes/:?]

**To Reproduce**
    @Test
    public void testbug() throws Exception {
        String SampleXml = "" +
                "<NativeDicomModel xml:space=\"preserve\">\n" +
                "   <DicomAttribute PrivateCreator=\"EditStatus\" tag=\"00610004\" vr=\"US\">\n" +
                "      <Value number=\"1\">1</Value>\n" +
                "   </DicomAttribute>\n" +
                "</NativeDicomModel>";

        Xml2Dcm.xml2DicomByteArray(SampleXml);
    }

**Expected behavior**/**Additional context**
The above test is a stripped down test.  The original used an XML that was several pages long.  The original test parsed the xml into dicom successfully.

Previously we used Dcm4Che 5.19.1 and 5.22.5 and the tests passed.  I tried an update to 5.22.6 and the tests failed.
It appears that the change to org.dcm4che3.util.StringUtils.java on Oct 8 2020 likely introduced this issue.

**Desktop (please complete the following information):**
 - OS: Mac Catalina 10.15.7
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by gunterze** [comment]
```
at org.dcm4che3.tool.xml2dcm.Xml2Dcm.xml2DicomOutputStream(Xml2Dcm.java:116) ~[classes/:?]
at org.dcm4che3.tool.xml2dcm.Xml2Dcm.xml2DicomByteArray(Xml2Dcm.java:97) ~[classes/:?]
```
do not exists in {Xml2Dcm.java](https://github.com/dcm4che/dcm4che/blob/generic-config/dcm4che-tool/dcm4che-tool-xml2dcm/src/main/java/org/dcm4che3/tool/xml2dcm/Xml2Dcm.java#L97-L116)
