### ISSUE TITLE
Error converting DICOM to JPG - Unsupported Transfer Syntax

### ISSUE THREAD

**Issue by tecsal** [dcm4che/dcm4che#908]
Hello, we had this error with all the images generated from one modality (a mammograph ) in one of our clients who used dcm4chee ( dcm4chee-arc-5.18.0 ) as pacs:

```
java.lang.UnsupportedOperationException: Unsupported Transfer Syntax: 1.2.840.10008.1.2
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.setMetadata(DicomImageReader.java:796)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.readMetadata(DicomImageReader.java:713)
	at org.dcm4che3.imageio.plugins.dcm.DicomImageReader.read(DicomImageReader.java:452)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.readImage(Dcm2Jpg.java:382)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.convert(Dcm2Jpg.java:361)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.mconvert(Dcm2Jpg.java:346)
	at org.dcm4che3.tool.dcm2jpg.Dcm2Jpg.main(Dcm2Jpg.java:315)
```

Error occurs when calling the Wado WS to obtain a thumbnail. It can be reproduced too with the dcm2jpg tool ( dcm4che-5.19.0 ). Here some examples:

[A03D69C8.zip](https://github.com/dcm4che/dcm4che/files/6096126/A03D69C8.zip)
[A03D69E5.zip](https://github.com/dcm4che/dcm4che/files/6096130/A03D69E5.zip)

We tried, along with technicians, to send images in many different way from the modality, but nothing to do; still having this issue.

We also have problem to display those images with our cornerstone.js customized viewer. Seem the pixel data doesn't fit some requirement... 

The strange thing is that Weasis viewer does open and display those images perfectly :-(

Is there a way to convert/transcode those DICOM to compatible DICOM ? It tried with dcm2dcm --j2ki , but get this error:

Mar 06, 2021 6:46:51 PM org.opencv.osgi.OpenCVNativeLoader init
INFO: Successfully loaded OpenCV native library.
18:46:51,968 DEBUG - Compressor: org.dcm4che3.opencv.NativeJ2kImageWriter
Failed to transcode /home/clancien/Downloads/1.2.840.113681.2886740005.1614844722.4812.42227/DICOM/A03D69AE/A03D69C7/A03D69C8: null
```
java.io.EOFException
	at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:74)
	at org.dcm4che3.io.DicomInputStream.readFully(DicomInputStream.java:394)
	at org.dcm4che3.imageio.codec.Transcoder.readFully(Transcoder.java:679)
	at org.dcm4che3.imageio.codec.Transcoder.readFrame(Transcoder.java:657)
	at org.dcm4che3.imageio.codec.Transcoder.compressPixelData(Transcoder.java:473)
	at org.dcm4che3.imageio.codec.Transcoder.processPixelData(Transcoder.java:425)
	at org.dcm4che3.imageio.codec.Transcoder.access$200(Transcoder.java:70)
	at org.dcm4che3.imageio.codec.Transcoder$1.readValue(Transcoder.java:383)
	at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:534)
	at org.dcm4che3.imageio.codec.Transcoder.transcode(Transcoder.java:362)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcodeWithTranscoder(Dcm2Dcm.java:411)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.transcode(Dcm2Dcm.java:350)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:341)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.mtranscode(Dcm2Dcm.java:318)
	at org.dcm4che3.tool.dcm2dcm.Dcm2Dcm.main(Dcm2Dcm.java:290)
```

And here, if need a comparison, same client, same technicians, other but similar mammograph; but producing compatible DICOM:
[A25D3FBF_OK.zip](https://github.com/dcm4che/dcm4che/files/6096145/A25D3FBF_OK.zip)

Appreciate some help :-)

**Comment by gunterze** [comment]
The Transfer Syntax in the File Meta Information
```
$ dcmdump A03D69C8 | head -n6
0: [0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
132: (0002,0000) UL #4 [182] FileMetaInformationGroupLength
144: (0002,0001) OB #2 [0\1] FileMetaInformationVersion
158: (0002,0002) UI #30 [1.2.840.10008.5.1.4.1.1.1.2.1] MediaStorageSOPClassUI
196: (0002,0003) UI #48 [1.2.840.113681.2886740005.1614844722.4812.42232] Medi
252: (0002,0010) UI #20 [1.2.840.10008.1.2.1] TransferSyntaxUID
```
claims uncompressed Pixel Data, but the contained Pixel Data is compressed
```
$ dcmdump A03D69C8 | tail -n4
6792: (7FE0,0010) OB #-1 PixelData
6804: >(FFFE,E000) #0 [] Item
6812: >(FFFE,E000) #12206838 [-1\-40\-1\-61\0\11\14\16\0\13\0\1\1\17\0\-1\-35\
12213658: (FFFE,E0DD) #0 SequenceDelimitationItem
```
