### ISSUE TITLE
tag value too large, must be less than 2Gib

### ISSUE THREAD

**Issue by ebremer** [dcm4che/dcm4che#968]
Using dcm4che 5.23.3

Some of my DICOM files are throwing the following error:

org.dcm4che3.io.DicomStreamException: 0x676C1ECC tag value too large, must be less than 2Gib
        at org.dcm4che3.io.DicomInputStream.tagValueTooLargeException(DicomInputStream.java:416)
        at org.dcm4che3.io.DicomInputStream.readHeader(DicomInputStream.java:455)
        at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:557)
        at org.dcm4che3.io.DicomInputStream.readDataset(DicomInputStream.java:503)
        at org.dcm4che3.io.DicomInputStream.readDataset(DicomInputStream.java:496)

dcmdump will do the same thing with:

12:51:54,827 WARN  - Unrecognized VR code: 0000H - treat as UN
12:51:54,828 WARN  - IOException during read of (0000,0000) #-2063728384 @ 201036
java.io.EOFException
        at org.dcm4che3.io.DicomInputStream.readValue(DicomInputStream.java:779)
        at org.dcm4che3.tool.dcmdump.DcmDump.readValue(DcmDump.java:123)
        at org.dcm4che3.io.DicomInputStream.readAttributes(DicomInputStream.java:534)
        at org.dcm4che3.io.DicomInputStream.readDataset(DicomInputStream.java:468)
        at org.dcm4che3.tool.dcmdump.DcmDump.parse(DcmDump.java:87)
        at org.dcm4che3.tool.dcmdump.DcmDump.main(DcmDump.java:247)

**Comment by gunterze** [comment]
Guess your DICOM files are corrupted and the error message is just misleading - or are the files reallly larger than 2GiB

**Comment by ebremer** [comment]
they are smaller.  as far as corruption, possible, they seem to be all related to a particular model/device (Toshiba).  I did read some related issues to this error:
https://githubmemory.com/repo/dcm4che/dcm4che/issues/918
but I will have to dog deeper into the data to find out if the same thing is happening.

**Comment by ebremer** [comment]
Okay, I took one of the problem files which is about 500k.  Ran the debugger on the code until it failed.  It figures out the VR code is "SQ", but it calculates length as -1 which then throws tagValueTooLargeException() at 455:DicomInputStream.  buf[] contains (viewed with NetBeans):
[0] = 8
[1] = 0
[2] = 50
[3] = 16
[4] = -1  (in file using a binary viewer is 83)
[5] = -1 (in file using a binary viewer is 81)
[6] = -1 (in file using a binary viewer is 00)
[7] = -1 (in file using a binary viewer is 00)
[8] = 0 (in file using a binary viewer is 255)
[9] = 0 (in file using a binary viewer is 255)
[10] = 0 (in file using a binary viewer is 255)
[11] = 0 (in file using a binary viewer is 255)

**Comment by gunterze** [comment]
Simplest would be if you can share one object. Or at least the last lines of dcmdump, before
```
12:51:54,827 WARN - Unrecognized VR code: 0000H - treat as UN
12:51:54,828 WARN - IOException during read of (0000,0000) #-2063728384 @ 201036
java.io.EOFException
:
```

**Comment by ebremer** [comment]
. . . clipped from rest of dump . . .
3598: (7FD1,1030) UL #4 [3] MultiResolutionLevels
3610: (7FD1,1040) UL #16 [64\128\256\512] SubbandRows
3634: (7FD1,1050) UL #16 [64\128\256\512] SubbandColumns
3658: (7FD1,1060) UL #16 [3540\9664\35312\131820] SubbandBytecounts
3682: (7FE0,0010) OB #-1 PixelData
3694: >(FFFE,E000) #0 [] Item
3702: >(FFFE,E000) #186276 [-1\-40\-1\-32\0\15\76\74\73\70\0\1\0\0\0\0\0\0\0\-
11:33:18,334 WARN  - Unrecognized VR code: 9FCAH - treat as UN
dcmdump: 0xC57AB75C tag value too large, must be less than 2Gib

**Comment by gunterze** [comment]
```
[0] = 8
[1] = 0
[2] = 50
[3] = 16
[4] = -1 (in file using a binary viewer is 83)
[5] = -1 (in file using a binary viewer is 81)
[6] = -1 (in file using a binary viewer is 00)
[7] = -1 (in file using a binary viewer is 00)
[8] = 0 (in file using a binary viewer is 255)
[9] = 0 (in file using a binary viewer is 255)
[10] = 0 (in file using a binary viewer is 255)
[11] = 0 (in file using a binary viewer is 255)
```
looks like an Implicit VR Little Endian encoded _(0008,1032) Procedure Code Sequence_ with undefined length, but instead of a following _(FFFE,E000) Item_ or _(FFFE,E0DD) Sequence Delimitation Item_, following bytes are 0.

**Comment by gunterze** [comment]
```
3702: >(FFFE,E000) #186276 [-1-40-1-32\0\15\76\74\73\70\0\1\0\0\0\0\0\0\0-
11:33:18,334 WARN - Unrecognized VR code: 9FCAH - treat as UN
dcmdump: 0xC57AB75C tag value too large, must be less than 2Gib
```
Looks that the encoded Data Fragment Length: #`186276` does not match with the actual item length, so some bytes of the JPEG stream are decoded as tag, VR and value length.

**Comment by ebremer** [comment]
Would you say this is problem in the vendor's DICOM files or a limitation of dcm4che?

**Comment by gunterze** [comment]
It's an issue of the file - how you got it from the acquisition device?
