### ISSUE TITLE
DICOM image with unusual tag fails guessTransferSytax

### ISSUE THREAD

**Issue by ryleyb** [dcm4che/dcm4che#997]
**Describe the bug**
I have an image that I was unable to send to storescp.  The stack trace is this:

```
18:31:11,229 INFO  - STORESCP<-STORESCU(1): processing 1:C-STORE-RQ[pcid=5, prior=0
  cuid=1.2.840.10008.5.1.4.1.1.7 - Secondary Capture Image Storage
  iuid=1.2.840.113681.2886995978.1592292307.5396.4381 - ?
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian] failed. Caused by:
org.dcm4che3.net.service.DicomServiceException: org.dcm4che3.io.DicomStreamException: Not a DICOM Stream
        at org.dcm4che3.tool.storescp.StoreSCP$1.store(StoreSCP.java:133)
        at org.dcm4che3.net.service.BasicCStoreSCP.onDimseRQ(BasicCStoreSCP.java:72)
        at org.dcm4che3.net.service.DicomServiceRegistry.onDimseRQ(DicomServiceRegistry.java:86)
        at org.dcm4che3.net.ApplicationEntity.onDimseRQ(ApplicationEntity.java:474)
        at org.dcm4che3.net.Association.onDimseRQ(Association.java:755)
        at org.dcm4che3.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:466)
        at org.dcm4che3.net.Association.handlePDataTF(Association.java:738)
        at org.dcm4che3.net.State$4.onPDataTF(State.java:108)
        at org.dcm4che3.net.Association.onPDataTF(Association.java:734)
        at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:177)
        at org.dcm4che3.net.Association$2.run(Association.java:571)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.dcm4che3.io.DicomStreamException: Not a DICOM Stream
        at org.dcm4che3.io.DicomInputStream.guessTransferSyntax(DicomInputStream.java:931)
        at org.dcm4che3.io.DicomInputStream.<init>(DicomInputStream.java:138)
        at org.dcm4che3.io.DicomInputStream.<init>(DicomInputStream.java:133)
        at org.dcm4che3.tool.storescp.StoreSCP.storeTo(StoreSCP.java:173)
        at org.dcm4che3.tool.storescp.StoreSCP.access$400(StoreSCP.java:84)
        at org.dcm4che3.tool.storescp.StoreSCP$1.store(StoreSCP.java:121)
        ... 13 more
```

**To Reproduce**
I can't share the image, but here's a partial hexdump from the start:
```
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000080  44 49 43 4d 02 00 00 00  55 4c 04 00 b4 00 00 00  |DICM....UL......|
00000090  02 00 01 00 4f 42 00 00  02 00 00 00 00 01 02 00  |....OB..........|
...
00000140  50 35 31 37 03 00 09 00  53 53 02 00 00 00 05 00  |P517....SS......|
00000150  05 00 43 53 0c 00 4e 6f  76 61 52 61 64 20 36 2e  |..CS..NovaRad 6.|
00000160  30 20 05 00 0b 00 4c 4f  06 00 47 41 2d 43 4f 46  |0 ....LO..GA-COF|
```

In trying to track down the issue, I added some debugging in `DicomInputStream`'s `guessTransferSyntax`.  To be clear, I have no idea what I'm doing, but a few things I saw:

1. This only gets called with the 2nd 132 bytes, not the 1st 132 bytes (so it starts with `0300 0900 5353 0200 00`).  When running say dcmdump, it gets the DICM bit so follows a different path
2. The (0003,0009) SS tag doesn't get identified so it returns `VR.UN` and it gives up.

**Expected behavior**
Ideally this image would work fine, all the other tools manage to understand it...

**Additional context**
This is running 5.23.3

**Comment by gunterze** [comment]
[DICOM PS 3.5: 7.1 Data Elements](http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_7.1)

> Private Data Elements have an odd Group Number that is not (0001,eeee), (0003,eeee), (0005,eeee), (0007,eeee), or (FFFF,eeee). Private Data Elements are discussed further in Section 7.8.

**Comment by ryleyb** [comment]
Thanks Gunter - that makes sense.  How should I have caught that (besides knowing the spec obviously) - is there a tool in the suite that would tell me this?  I looked at `dcmvalidate` but wasn't sure how or if it applied...

**Comment by gunterze** [comment]
I will try to reproduce the failure and find a workaround - but it will not be included in 5.24.0 which I am currently releasing..

**Comment by ryleyb** [comment]
I've just gotten another sample that's basically the same thing - after the 0002 Group, we get a `(0003,0009)` SS followed by a couple other elements in the 0003 Group.  Consistent results (this error).

**Comment by gunterze** [comment]
Could not reproduce the issue with 5.24.0:
```
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
*
00000080: 4449 434d 0200 0000 554c 0400 c000 0000  DICM....UL......
00000090: 0200 0100 4f42 0000 0200 0000 0001 0200  ....OB..........
...
00000150: 0300 0900 5353 0200 0000 0500 0500 4353  ....SS........CS
00000160: 0c00 4e6f 7661 5261 6420 362e 3020 0800  ..NovaRad 6.0 ..
00000170: 0800 4353 2400 4445 5249 5645 445c 5052  ..CS$.DERIVED\PR
...
```console
dcmdump obj.dcm
0: [0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
132: (0002,0000) UL #4 [192] FileMetaInformationGroupLength
144: (0002,0001) OB #2 [0\1] FileMetaInformationVersion
...
336: (0003,0009) SS #2 [0] 
346: (0005,0005) CS #12 [NovaRad 6.0] 
366: (0008,0008) CS #36 [DERIVED\PRIMARY\WHOLE BODY\EMISSION] ImageType
...
```

**Comment by ryleyb** [comment]
Attached is an example that fails for me on 5.24.0.
[failing-headers.zip](https://github.com/dcm4che/dcm4che/files/7138836/failing-headers.zip)

**Comment by ryleyb** [comment]
I've verified that this is entirely an issue on my end.  Thank you for all your help and sorry for wasting your time.
